[i18n] Added Arabic translation
RocketChat/Rocket.Chat.ReactNative pull request #1941
Opened 2020-03-25 09:04 UTC by AlkindiX

@RocketChat/ReactNative
This new pull request add Arabic translation to Rocket chat Reactive project.

2020-03-25 09:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative?pullRequest=1941) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative?pullRequest=1941) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.ReactNative?pullRequest=1941) it.</sub>

2020-03-25 10:06 UTC, AlkindiX commented
Please Review

2020-03-26 12:06 UTC, diegolmello commented
Thanks for opening, @AlkindiX.
We'll take a look soon.

2020-10-04 23:56 UTC, abalhamoud requested changes
Some minor fixes and suggestions on the translation. :)

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	'error-file-too-large': 'الملف كبير جدا',
```suggestion
	'error-file-too-large': 'ًحجم الملف كبير جدا',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	'error-importer-not-defined': 'المستورد غير معرف بطريقة صحيحة, ينقصها فئة اﻹستيراد.',
```suggestion
	'error-importer-not-defined': 'المستورد غير معرف بطريقة صحيحة. نوع اﻹستيراد مفقود .',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	'error-invalid-custom-field-name': 'إسم الحقل المخصص غير صالح. استخدم الحروف والأرقام والواصلات والشرطات السفلية فقط',
```suggestion
	'error-invalid-custom-field-name': 'اسم الحقل المخصص غير صالح. استخدم الحروف والأرقام والواصلات والشرطات السفلية فقط',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	'error-invalid-date': 'تالتاريخ غير صالح.',
```suggestion
	'error-invalid-date': 'التاريخ غير صالح.',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	'error-invalid-from-address': 'لقد أبلغت عن عنوان غير صالح (من).',
```suggestion
	'error-invalid-from-address': 'عنوان غير صالح في خانة (من).',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	'error-invalid-room-name': '{{room_name}} ليس اسم الغرفة صالح',
```suggestion
	'error-invalid-room-name': '{{room_name}} اسم الغرفة غير صالح',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	'error-invalid-room-type': '{{type}} ليس نوع الغرفة صالحا.',
```suggestion
	'error-invalid-room-type': '{{type}} نوع الغرفة غير صالح.',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	'error-invalid-urls': 'عناوين  غير صالحة',
```suggestion
	'error-invalid-urls': 'عناوين غير صالحة',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	'error-invalid-user': 'مستخدم  غير صالح',
```suggestion
	'error-invalid-user': 'مستخدم غير صالح',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	'error-invalid-username': 'إسم المستخدم  غير صالح',
```suggestion
	'error-invalid-username': 'إسم المستخدم غير صالح',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	'error-invalid-webhook-response': 'الرد التلقائي من العنوان أستجاب برمز مغاير عن المفترض 200',
```suggestion
	'error-invalid-webhook-response': 'الرد التلقائي من العنوان استجاب برمز مغاير عن المفترض 200',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	'error-message-size-exceeded': 'حجم الرسالة تجاوز المحدد الحجم المحدد له (Message_MaxAllowedSize)',
```suggestion
	'error-message-size-exceeded': 'حجم الرسالة تجاوز الحد المسموح (Message_MaxAllowedSize)',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	'error-user-has-no-roles': 'يس للمستخدم أدوار',
```suggestion
	'error-user-has-no-roles': 'ليس للمستخدم أدوار',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	'error-user-registration-disabled': 'تم تعطيل تسجيل المستخدم',
```suggestion
	'error-user-registration-disabled': 'التسجيل معطل',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	'error-user-registration-secret': 'تسجيل المستخدم مسموح به فقط عبر عنوان الويب السري',
```suggestion
	'error-user-registration-secret': 'التسجيل مسموح به فقط عبر عنوان الويب السري',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Actions: 'أجراءات',
```suggestion
	Actions: 'الإجراءات',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Admin_Panel: 'لوحة الادارة',
```suggestion
	Admin_Panel: 'لوحة الإدارة',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	alerts: 'إنذارات',
```suggestion
	alerts: 'الإنذارات',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	archive: 'أرشيف',
is this used for the action "archive"? if so it then it should be: 
```suggestion
	archive: 'أرشفة',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Are_you_sure_question_mark: 'هل أنت متأكد',
```suggestion
	Are_you_sure_question_mark: 'هل أنت متأكد؟',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Are_you_sure_you_want_to_leave_the_room: 'متأكد أنك تريد مغادرة الغرفة {{room}}?',
```suggestion
	Are_you_sure_you_want_to_leave_the_room: 'متأكد من مغادرة الغرفة {{room}}?',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Block_user: 'حضر مستخدم',
```suggestion
	Block_user: 'حظر المستخدم',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	By_proceeding_you_are_agreeing: 'من خلال المتابعة, أنت توافق على',
```suggestion
	By_proceeding_you_are_agreeing: 'من خلال المتابعة، أنت توافق على',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Call_already_ended: 'تم إنهاء المكالمة بالفعل!',
```suggestion
	Call_already_ended: 'انتهت المكالمة بالفعل!',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Choose: 'أختر',
```suggestion
	Choose: 'اختر',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Copied_to_clipboard: 'نسخ إلى الحافظة!',
```suggestion
	Copied_to_clipboard: 'تم النسخ للحافظة!',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Clear_cache: 'امسح ذاكرة التخزين المؤقت للخادم',
```suggestion
	Clear_cache: 'امسح ذاكرة التخزين المؤقتة للخادم',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Dark_level: 'مستوى سمة الداكنة',
```suggestion
	Dark_level: 'مستوى السمة الداكنة',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Delete_Room_Warning: 'سيؤدي حذف غرفة إلى حذف جميع الرسائل المنشورة داخل الغرفة. هذا لا يمكن التراجع عنها.',
```suggestion
	Delete_Room_Warning: 'سيؤدي حذف الغرفة إلى حذف جميع الرسائل المنشورة. لا يمكن التراجع بعد الحذف.',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Email: 'بريد الإلكتروني',
```suggestion
	Email: 'البريد الإلكتروني',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	EMAIL: 'بريد الإلكتروني',
```suggestion
	EMAIL: 'البريد الإلكتروني',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	email: 'بريد الإلكتروني',
```suggestion
	email: 'البريد الإلكتروني',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	File_name: 'إسم الملف',
```suggestion
	File_name: 'اسم الملف',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	For_your_security_you_must_enter_your_current_password_to_continue: 'من أجل أمانك ، يجب عليك إدخال كلمة المرور الحالية للمتابعة',
```suggestion
	For_your_security_you_must_enter_your_current_password_to_continue: 'من أجل حمايتك، يجب عليك إدخال كلمة المرور الحالية للمتابعة',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Full_table: 'انقر لرؤية الجدول الكامل',
```suggestion
	Full_table: 'انقر لرؤية الجدول كاملاً',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Group_by_favorites: 'مجموعة مفضلة',
```suggestion
	Group_by_favorites: 'جمع حسب المفضل',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Message_HideType_uj: 'مستخدم إنضم',
```suggestion
	Message_HideType_uj: 'مستخدم انضم',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Message_HideType_ut: 'انضم المستخدم المحادثة',
```suggestion
	Message_HideType_ut: 'انضم المستخدم للمحادثة',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Message_HideType_subscription_role_added: 'تم تعيين وظيفة',
```suggestion
	Message_HideType_subscription_role_added: 'تم تعيين دور جديد',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Message_HideType_subscription_role_removed: 'وظيفة أصبحت غير معرفة',
```suggestion
	Message_HideType_subscription_role_removed: 'حذف دور',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Join_the_community: 'إنضم للمجتمع',
```suggestion
	Join_the_community: 'انضم للمجتمع',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Join: 'إنضم',
```suggestion
	Join: 'انضم',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Message_Reported: 'تم تبليغ الرسالة',
```suggestion
	Message_Reported: 'تم التبليغ على الرسالة',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	name: 'إسم',
```suggestion
	name: 'اسم',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Name: 'إسم',
```suggestion
	Name: 'اسم',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Next: 'تالي',
```suggestion
	Next: 'التالي',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	No_messages_yet: 'لا رسالة حتى اﻵن',
```suggestion
	No_messages_yet: 'لا رسائل حتى اﻵن',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	No_Read_Receipts: 'لا قراءة الإيصالات',
```suggestion
	No_Read_Receipts: 'لا إيصالات القراءة',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Nothing: 'Nothing',
```suggestion
	Nothing: 'لا شيء',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Nothing_to_save: 'لا شي للحفظ!',
```suggestion
	Nothing_to_save: 'لا شيء للحفظ!',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Only_authorized_users_can_write_new_messages: 'Only authorized users can write new messages',
```suggestion
	Only_authorized_users_can_write_new_messages: 'يمكن للمستخدمين المصرح لهم فقط كتابة رسائل جديدة',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Open_emoji_selector: 'Open emoji selector',
```suggestion
	Open_emoji_selector: 'افتح محدد الإيموجي',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Overwrites_the_server_configuration_and_use_room_config: 'يمكن للمستخدمين المصرح لهم فقط كتابة رسائل جديدة',
```suggestion
	Overwrites_the_server_configuration_and_use_room_config: 'استخدم إعدادات الغرفة بدلاً من الإعدادات الافتراضية',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Please_enter_your_password: 'الرجاء أدخل الرقم السري',
```suggestion
	Please_enter_your_password: 'الرجاء إدخال الرمز السري',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Password: 'رقم سري',
```suggestion
	Password: 'الرمز السري',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Quote: 'Quote',
```suggestion
	Quote: 'اقتباس',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Send_to: 'ارسال إلر...',
```suggestion
	Send_to: 'إرسال إلى...',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Sent_an_attachment: 'تم ارسال مرفق',
```suggestion
	Sent_an_attachment: 'تم ارسال المرفق',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	New_line: 'خط جديد',
```suggestion
	New_line: 'سطر جديد',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	You_are_offline: 'انت غير متصل',
```suggestion
	You_are_offline: 'أنت غير متصل',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Video_call: 'مكالمة فيديوا',
```suggestion
	Video_call: 'مكالمة فيديو',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Show_Unread_Counter: 'Sإظهار العداد غير المقروء',
```suggestion
	Show_Unread_Counter: 'إظهار عدد غير المقروء',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Show_Unread_Counter_Info: 'تم عرض العداد غير المقروء كشارة على يمين القناة في القائمة',
```suggestion
	Show_Unread_Counter_Info: 'يتم عرض العدد غير المقروء كشارة على يمين القناة في القائمة',
```

2020-10-04 23:56 UTC, abalhamoud commented on app/i18n/locales/ar.js
> +	Take_a_video: 'التقاط فيديوا',
```suggestion
	Take_a_video: 'التقاط فيديو',
```

2020-10-05 13:35 UTC, diegolmello commented
Hey, @abalhamoud.
This PR is quite old, so there're missing keys.
Do you mind opening a new one?
I'll make sure @AlkindiX is marked as co-author.
Thank you, guys.

2020-10-05 14:36 UTC, AlkindiX commented
I forgot about this PR. It was a while ago. @abalhamoud  thank you for your contribution. Too many commits to merge. @diegolmello you can close this commit and @abalhamoud to open a new one instead of this with all the corrections and new keys.

Thanks

2020-10-05 14:43 UTC, AlkindiX reviewed
I just reviewed most the changes

2020-10-06 20:38 UTC, abalhamoud commented
Sure @diegolmello I will open a new PR with the latest keys. Thanks to @AlkindiX for the contribution.

2020-10-07 14:47 UTC, AlkindiX commented
Closing this pull request

2020-10-07 14:47 UTC, closed without merging

2020-10-08 19:25 UTC, abalhamoud commented
@diegolmello I have opened a new PR #2537 for the translation. Please check.

2020-10-08 19:36 UTC, diegolmello commented
I'm going to review it soon.
Thanks, guys.