[NEW] Show to user a history of recent serves
RocketChat/Rocket.Chat.ReactNative pull request #2421
Opened 2020-08-24 03:20 UTC by EzequielDeOliveira

## Proposed changes

This PR create a list of serves that the user accessed as suggestions.
## Issue(s)	

closes #2348 
## How to test or reproduce

## Screenshots
![ezgif com-video-to-gif(42)](https://user-images.githubusercontent.com/37127457/91000445-9a545400-e59f-11ea-9365-fb5604e55bec.gif)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2020-08-26 13:57 UTC, EzequielDeOliveira commented
My bad, I'll take a look at this problem!

2020-09-11 14:11 UTC, djorkaeffalexandre requested changes

2020-09-11 16:16 UTC, diegolmello commented on app/views/NewServerView/ServerInput/Item.js
> +		paddingHorizontal: 15,
We need to refactor this kind of content soon.
Currently, most of the horizontal content paddings are 15.
Example: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/views/Styles.js#L11

Right now, it's better to keep this bad implementation.

2020-09-11 17:10 UTC, diegolmello approved these changes
LGTM

2020-09-11 17:10 UTC, merged

2020-09-11 17:25 UTC, didierm commented
@EzequielDeOliveira Thank you so much !
This allows us to force session expiration on mobile.

2020-10-02 08:10 UTC, aenonGit commented
@EzequielDeOliveira @diegolmello am I the only one experiecing crashes? On the open server, where I have a username/password account everything goes well but on my own server with custom oauth, when I click the server suggestion the app crashes

2020-10-02 12:20 UTC, diegolmello commented
> @EzequielDeOliveira @diegolmello am I the only one experiecing crashes? On the open server, where I have a username/password account everything goes well but on my own server with custom oauth, when I click the server suggestion the app crashes

@aenonGit Search for opened issues and open a new one (if you didn't find it) with detailed info is the only way to help you. PRs appreciated.

2020-10-27 16:23 UTC, devZer0 commented
the auto-logout with missing workspace url/history is a real bummer and a major reason why our community has problems accepting rocketchat as web/team chat.  

when will this fix be available in the app/play-store ?

2020-10-27 16:23 UTC, diegolmello commented
@devZer0 it's available on 4.11

2020-10-27 16:50 UTC, devZer0 commented
mhh, ok, i missed that. you are right. sorry. 

but i think this could be solved more intelligently by showing the last used server in the dialogue _before_ the dialogue for entering that url another time or selecting the old one from the history.  

most non-technical users will be overchalleged by this when the suddenly being thrown out of the chat and need to re-enter the server url.  many won't try to re-type something they don't know and most of our users in our community will not know that url weeks after usage and need to ask for it another time.

it's like throwing someone out of a house with a thousand doors with some remark way down on the pavement, which door he needs to choose for re-entering the house.

2020-10-27 17:04 UTC, diegolmello commented
Got it, but it is redirecting you automatically after server logs you out.
Maybe you can update, test and give your feedback again later.
WDYT?

2020-10-27 17:06 UTC, devZer0 commented
sounds promising - but i have 4.11 and it didn't.  i cannot force server-side login timeout (as i don't own this server) for retry, so need to wait for another occurence...

2020-10-27 17:17 UTC, diegolmello commented
Ok. Open a new issue when it happens with details.
A video would be good, just to be sure we're talking about the same thing.