[I18n] Improve Simplified Chinese(zh_CN) language file
RocketChat/Rocket.Chat.ReactNative pull request #2466
Opened 2020-09-15 09:02 UTC by David-Tsui

Improve Simplified Chinese language.

I do use the en.js to translate.

Some words or sentences need to be improved or a better translator.

2020-09-15 13:52 UTC, diegolmello requested changes
Same as https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2465#pullrequestreview-488704148
I got it that you add missing `en` strings, but they were falling back to `en` anyway.

2020-09-16 07:00 UTC, David-Tsui commented
@diegolmello This PR has also fixed in the same way as #2465 . Thanks for your review!

2020-09-16 19:24 UTC, diegolmello approved these changes

2020-09-16 19:25 UTC, merged

2020-09-16 19:25 UTC, diegolmello commented
@David-Tsui Both PRs merged.
Thank you!