[i18n] Add missing Russian strings
RocketChat/Rocket.Chat.ReactNative pull request #2555
Opened 2020-10-14 05:42 UTC by ankar84

## Proposed changes
Russian translation was missing a lot of strings, this PR adds all the missing ones and fixes some of the existing strings.

## Issue(s)	
closes #2554

## How to test or reproduce

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2020-10-14 05:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative?pullRequest=2555) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative?pullRequest=2555) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Карлан Антон Андреевич<br/>:x: ankar84<br/><hr/>**Карлан Антон Андреевич** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.ReactNative?pullRequest=2555) it.</sub>

2020-10-14 07:45 UTC, ankar84 commented
**Карлан Антон Андреевич** it's me actually pulled commits with unset properly  git client on my machine. I don't know how get rid of that now.

2020-10-14 12:07 UTC, ankar84 commented
@Pitstopper can you take a look on proposed changes?
I see, that you [worked](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/381) on Russian locale in that repo.
Thanks!

2020-10-14 13:14 UTC, Pitstopper requested changes
Hey! You have done a great job! My respect!  But there are some points that need to be fixed for better display in the Russian version of the rocketchat client.

2020-10-14 13:14 UTC, Pitstopper commented on app/i18n/locales/ru.js
> +	Dark_level: 'Уровень Темной Темы',
Maybe - "Степень затемнения" или "Уровень затемненности"?

2020-10-14 13:14 UTC, Pitstopper commented on app/i18n/locales/ru.js
> +	Invalid_or_expired_invite_token: 'Токен приглашение не валидный или с истекшим сроком действия',
Maybe - "Токен приглашения не действителен или с истекшим сроком действия"?

2020-10-14 13:14 UTC, Pitstopper commented on app/i18n/locales/ru.js
> +	Uses_server_configuration: 'Uses server configuration',
Translate this please! (If it needs to be translated...)

2020-10-14 13:14 UTC, Pitstopper commented on app/i18n/locales/ru.js
> +	Local_authentication_biometry_fallback: 'Использовать паскод',
Maybe - пасскод or пасс-код?

2020-10-14 13:31 UTC, ankar84 commented on app/i18n/locales/ru.js
> +	Create_Direct_Messages: 'Создать Личное сообщение',
Agree with you. I just try to translate with accurate accordance to English variant - where all was capitalized, I did same in Russian.
But yes, I will fix that, thanks!

2020-10-14 13:36 UTC, ankar84 commented on app/i18n/locales/ru.js
> +	Overwrites_the_server_configuration_and_use_room_config: 'Overwrites the server configuration and use room config',
Sure, I will definitely translate `Overwrites_the_server_configuration_and_use_room_config: Overwrites the server configuration and use room config,` in next commit
But I want to ask @diegolmello where is OR and OS is applied? Is that OS is for Operating System or something else? OR is like programmers `||` or what?

2020-10-14 14:02 UTC, diegolmello commented on app/i18n/locales/ru.js
> +	Overwrites_the_server_configuration_and_use_room_config: 'Overwrites the server configuration and use room config',
- `OR` is literal and used with a separator on login.

```
login with services

OR

login with user/password
```

- `OS` is `Operating System` and is used on Omnichannel.

2020-10-14 14:24 UTC, ankar84 commented on app/i18n/locales/ru.js
> +	Local_authentication_biometry_fallback: 'Использовать паскод',
I though maybe simple `пароль`?
I did a `паскод` translate for `passcode` to make some difference between regular user password, but simple translate for `passcode` is `пароль`.
What do you think?

2020-10-14 14:41 UTC, Pitstopper commented on app/i18n/locales/ru.js
> +	Local_authentication_biometry_fallback: 'Использовать паскод',
Sounds good!

2020-10-15 06:44 UTC, Pitstopper approved these changes
Well done :+1:

2020-11-03 19:26 UTC, diegolmello commented
@ankar84 can you update?

2020-11-04 02:45 UTC, ankar84 commented
> @ankar84 can you update?

@diegolmello I don't know how to do it now actually.
I think is something like:
1. Somehow fork again https://github.com/RocketChat/Rocket.Chat.ReactNative/ or somehow clone or something to my repo
2. Compare that refreshed up-to-date repo to my russian-strings branch and translate new missing strings.

But the problem is I really don't know actual steps (commands) to do that.
For me it's better to merge that PR and then I start from scratch and translate new missing strings.

2020-11-04 03:14 UTC, ankar84 commented
Oh, I think I broke everything when try to resolve conflicts.
So, let that PR lost in history...

2020-11-04 12:24 UTC, diegolmello reviewed
@ankar84 I've added missing `en` strings on this commit: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2555/commits/0ddd9db7fa8851f414d7054ecf4d7c59a36b0320

Can you translate them and send me on DM (then I can add them here)?
Thanks!

2020-11-04 13:32 UTC, ankar84 commented
> @ankar84 I've added missing `en` strings on this commit: [0ddd9db](https://github.com/RocketChat/Rocket.Chat.ReactNative/commit/0ddd9db7fa8851f414d7054ecf4d7c59a36b0320)
> 
> Can you translate them and send me on DM (then I can add them here)?
> Thanks!

@diegolmello done with your help.

2020-11-04 13:35 UTC, diegolmello approved these changes
LGTM

2020-11-04 13:38 UTC, merged