[WIP] - Replies don't render images
RocketChat/Rocket.Chat.ReactNative pull request #2564
Opened 2020-10-15 18:31 UTC by vitorl-s

Signed-off-by: Vitor Leal <vitor_leal2201@hotmail.com>

## Proposed changes
The reply of an image renders a full image in the reply box

## Issue(s)	
#704

## How to test or reproduce
Reply any message

## Screenshots

## Types of changes
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist
- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

2020-10-22 19:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative?pullRequest=2564) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative?pullRequest=2564) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: vitorl-s<br/>:x: fernand0aguilar<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.ReactNative?pullRequest=2564) it.</sub>

2020-10-29 18:46 UTC, djorkaeffalexandre requested changes

2020-10-29 18:46 UTC, djorkaeffalexandre commented
Make sure of add screenshots of your changes on PR's like this where screenshots can be applied.

2021-07-15 18:33 UTC, gerzonc commented
It seems to be working fine, can you resolve conflicts? Thanks for your contribution!

2022-03-15 20:15 UTC, diegolmello commented
Closing in favor of https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3883

2022-03-15 20:15 UTC, closed without merging