Add Video Thumbnail Support
RocketChat/Rocket.Chat.ReactNative pull request #2772
Opened 2021-01-07 08:08 UTC by pratyaksh123

## Proposed changes

Adds thumbnail support to Video files.

## Issue(s)	

Solves https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2746

## How to test or reproduce

## Screenshots
![](https://user-images.githubusercontent.com/55044774/103160409-c5271100-47fa-11eb-8b9b-fe03c5b9a299.jpeg)   --->>>    ![](https://user-images.githubusercontent.com/55044774/103160428-fe5f8100-47fa-11eb-8fd2-1220626f1ff6.jpeg)
Before and After

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments
- Currently, it can take up to 6-7 seconds to fetch a thumbnail, depending upon the size of the video ( The URL of the video is passed to ` VideoThumbnails.getThumbnailAsync(uri);`. 
- IMO, this load time can only be improved if this was to be done on the server or we were caching the videos locally.
- Also, we can add something like this ( https://github.com/chramos/react-native-skeleton-placeholder) as an indicator that the thumbnail is loading.

2021-01-07 09:42 UTC, pratyaksh123 commented
@diegolmello what do you think

2021-01-13 18:52 UTC, diegolmello commented
@pratyaksh123 Thanks for contributing.
We'll have to evaluate performance carefully first, as these 6~7 seconds you said aren't a great UX.
Do you know if we can cache videos somehow?

There's a lot of things going on right now, but I think I'll have time to review it next week.

2021-01-14 15:11 UTC, pratyaksh123 commented
Yeah alright I'll check it out

2021-01-18 10:05 UTC, pratyaksh123 commented
I got caching to work using expo's `FileSystem` Api. Will soon push.

2021-02-08 20:23 UTC, gerzonc requested changes

2021-02-08 20:23 UTC, gerzonc commented on app/containers/message/Video.js
> +						resizeMode='contain'
As mentioned earlier, this might look better on the chat if we set `resizeMode` to either `cover` or `center`.

2021-02-08 20:23 UTC, gerzonc commented on app/containers/message/Video.js
> +		left: 0
This is not being used, please remove it.

2021-02-15 12:22 UTC, pratyaksh123 commented
Alright, I'll push the changes soon. But can you also review this Video Caching PR https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2809 As this will significantly improve the time it takes to play videos and load thumbnails?

2021-03-08 18:10 UTC, diegolmello commented
Closing because it might not be needed after https://github.com/RocketChat/Rocket.Chat/pull/20986
Thanks a lot for your work here.
We're going to add you as contributor for the upcoming PR.

2021-03-08 18:10 UTC, closed without merging