[FIX] System message of e2e encryption missing
RocketChat/Rocket.Chat.ReactNative pull request #2888
Opened 2021-02-09 17:54 UTC by kresnaputra

## Proposed changes

Add more condition to render e2e text in message view if is toggle to on or off

## Issue(s)	

## How to test or reproduce

## Screenshots

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2021-02-09 18:35 UTC, diegolmello requested changes

2021-02-09 18:35 UTC, diegolmello commented on app/containers/message/utils.js
> +		return `This room's encryption has been disabled by ${ username }`;
You should add it to `en.js` and wrap it with `I18n.t()` as all the other messages.

2021-02-23 16:39 UTC, diegolmello requested changes
@kresnaputra can you add stories and screenshots to the description?

2021-02-23 18:08 UTC, kresnaputra commented
@diegolmello updated

2021-02-24 16:33 UTC, diegolmello approved these changes

2021-02-24 16:33 UTC, merged