[FIX] Add permissions to Redux store
RocketChat/Rocket.Chat.ReactNative pull request #2914
Opened 2021-02-17 19:59 UTC by kresnaputra

## Proposed changes

On Admin panel option is hidden after login, permissions aren't yet saved on local database yet causing the isAdmin logic to be false.
We have over 1000 permissions on the server, so we should only add to Redux those permissions we know are being called.

## Issue(s)	

## How to test or reproduce

## Screenshots

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2021-02-23 20:44 UTC, diegolmello requested changes

2021-02-23 20:44 UTC, diegolmello commented on app/views/SidebarView/index.js
> +		// const { isAdmin } = this.state;
Remove it

2021-02-23 20:44 UTC, diegolmello commented on app/views/RoomView/index.js
> +		// const { getPermissions } = this.props;
Remove it

2021-02-24 16:33 UTC, kresnaputra commented on app/lib/methods/getPermissions.js
> +	reduxStore.dispatch(clearPermissionsAction());
If I'm not forget you mentioned that permissions need have clear action to make sure that all permissions reduce get a fresh value

2021-02-25 16:41 UTC, diegolmello approved these changes

2021-02-25 16:41 UTC, merged