[CHORE] Subscribe to permissions
RocketChat/Rocket.Chat.ReactNative pull request #2993
Opened 2021-03-18 04:53 UTC by kresnaputra

## Proposed changes

If a permissions is changed by another user or on another client, the permissions's local database isn't change right away. So we need to subscribe or stream the permissions for update the local database every time permissions is change

## Issue(s)	

## How to test or reproduce

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2021-04-16 21:08 UTC, gerzonc approved these changes
LGTM

2021-04-19 19:51 UTC, diegolmello requested changes

2021-04-19 19:51 UTC, diegolmello commented on app/sagas/login.js
> +	RocketChat.subscribe('stream-notify-logged', 'permissions-changed');
Can you do it inside `RocketChat.getPermissions()`?

2021-04-19 19:51 UTC, diegolmello commented on app/actions/permissions.js
> +export function updatePermissions(id, roles) {
Plural, but updates a single permission.

2021-06-14 21:28 UTC, gerzonc approved these changes
LGTM

2021-07-01 13:57 UTC, merged