[Improvement] Improve mentions
RocketChat/Rocket.Chat.ReactNative pull request #2997
Opened 2021-03-18 17:33 UTC by sumukhah

This PR focuses on improving command, emoji, channel and user mentions and also Removed some unnecessary codes.

## Proposed changes

If a word starts with symbols(@, #, :, /) then only suggestion Pop ups.

## Issue(s)	

#2996 

## How to test or reproduce

Use the symbols in the middle of sentences, Pop-ups won't happen. If we use it at the beginning, it will pop up.
## Screenshots
**Using symbols at the beginning**
<img width="332" alt="Screenshot 2021-03-18 at 11 02 34 PM" src="https://user-images.githubusercontent.com/23723464/111670610-09481180-883e-11eb-83ff-4de7d525f4a0.png">

**Using symbols in the middle**
<img width="317" alt="Screenshot 2021-03-18 at 11 02 20 PM" src="https://user-images.githubusercontent.com/23723464/111670656-136a1000-883e-11eb-8dcc-6b66829f57b5.png">

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2021-03-18 17:36 UTC, diegolmello commented
@sumukhah It looks awesome! Can you write e2e tests? Thanks for your contribution!

2021-03-24 06:17 UTC, kresnaputra approved these changes
LGTM

2021-04-01 14:38 UTC, sumukhah commented
Please review @diegolmello

2021-04-01 20:27 UTC, diegolmello requested changes
@sumukhah that's a huge improvement on readability!
Left a few comments.
I can review it again as soon as you address them.
Thank you.

2021-04-01 20:27 UTC, diegolmello commented on app/containers/MessageBox/index.js
> +		const commandMention = lastWord.match(/^\//);
Slash commands should run only at the beginning of the message.

This should be considered/listened as slash commands:
```
/giphy
```

This should not:
```
Hey, check this: /giphy
```
In the message above, slash commands shouldn't be triggered when the user typed `/`

2021-04-01 20:27 UTC, diegolmello commented on app/containers/MessageBox/index.js
> -					if (!sharing) {
As wrote on this condition, slash commands shouldn't be triggered when `sharing === true`.
You can reproduce it by sharing images and then starting a message with `/`.

2021-04-01 20:27 UTC, diegolmello commented on app/containers/MessageBox/index.js
> -			if (slashCommand) {
Some slash commands run while typing, some run when the message is sent.
While typing, we need to evaluate the kind of command and act as expected.
If you try `/giphy` on https://open.rocket.chat, you'll see that you can play with gif previews while sending a message.
Open the app and type: `/giphy dog`

2021-04-04 22:23 UTC, sumukhah commented
@diegolmello thank you.. I have made some corrections to the slash command logic.
Please review

2021-04-04 22:34 UTC, sumukhah commented
@diegolmello 
made some changes to the slash command logic. Please review
Thank you

2021-04-05 17:24 UTC, diegolmello requested changes
@sumukhah Added a few commits to make it return data right after the symbol is recognised and fixed tests.
Just one thing left: since you're not tracking the cursor, a mention in the middle of a sentence doesn't work.

https://user-images.githubusercontent.com/804994/113603669-964ee100-961a-11eb-80ad-2ee2841b292b.mp4

2021-04-05 18:45 UTC, sumukhah commented
@diegolmello, Yes, I didn't notice the purpose of that !! 
I have changed some code in this commit. This would fix the issue with the cursor point.
Thank you 👍 

<img width="150" alt="Screenshot 2021-04-06 at 12 12 38 AM" src="https://user-images.githubusercontent.com/23723464/113612082-fd958100-966c-11eb-9ee6-46d61f70c496.png">

2021-04-05 18:58 UTC, sumukhah commented
🎉 I guess this would also fix #1580 now?

2021-04-05 18:59 UTC, sumukhah commented
> @sumukhah Added a few commits to make it return data right after the symbol is recognised and fixed tests.

🎉 I guess this would also fix #1580 now?

2021-04-07 18:56 UTC, diegolmello approved these changes
LGTM 🎉

2021-04-07 18:56 UTC, merged

2021-04-08 05:36 UTC, ankar84 commented
I'm testing 4.16.0 beta and can tell for sure that this PR fixes my issue https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2529 and probably that issue https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1580

@sumukhah great job!