[FIX] Pagination in SearchMessage by the javascript
RocketChat/Rocket.Chat.ReactNative pull request #3212
Opened 2021-06-15 19:13 UTC by reinaldonetof

## Proposed changes

Pagination on SearchMessageView

## Issue(s)	

There isn't pagination when search

## How to test or reproduce

- Go to a room
- Click on `search
- Search for a message

## Screenshots

<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</thead>
</tr>
<tbody>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/47038980/122110048-772bb700-cdf4-11eb-8672-4161c425aca3.png" height="450" />
</td>
<td>
<img src="https://user-images.githubusercontent.com/47038980/122110099-89a5f080-cdf4-11eb-9945-c6ba1d7b6b4b.png"  height="450"/>
</td>
</tr>
</tbody>
</table>

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2021-07-02 17:24 UTC, diegolmello requested changes

2021-07-02 17:24 UTC, diegolmello commented on app/views/SearchMessagesView/index.js
> +	onEndReached = () => {
We should be rerunning the request here.

2021-07-02 17:24 UTC, diegolmello commented on app/views/SearchMessagesView/index.js
> +const INITIAL_NUM_TO_RENDER = isTablet ? 20 : 12;
Not needed

2021-07-02 17:24 UTC, diegolmello commented on app/views/SearchMessagesView/index.js
> +			messagesFromQuery: [],
We might not need this

2021-07-02 17:24 UTC, diegolmello commented on app/views/SearchMessagesView/index.js
> +		this.count = QUERY_SIZE;
Make sure to reset this when search text changes

2021-07-22 14:02 UTC, diegolmello requested changes
Can you add a test plan for both normal and encrypted rooms?

2021-07-22 14:02 UTC, diegolmello commented on app/views/SearchMessagesView/index.js
> +	onEndReached = async() => {
Most of this function is duplicated from `this.search`.
Can we reuse it instead?

2021-07-22 14:02 UTC, diegolmello commented on app/views/SearchMessagesView/index.js
> +
Unnecessary empty space

2021-07-29 14:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative?pullRequest=3212) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative?pullRequest=3212) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: gerzonc<br/>:white_check_mark: reinaldonetof<br/>:white_check_mark: diegolmello<br/>:x: LevyCosta<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.ReactNative?pullRequest=3212) it.</sub>

2021-08-23 17:51 UTC, AlexAlexandre approved these changes
LGTM

2021-08-31 14:11 UTC, AlexAlexandre approved these changes
LGTM

2021-10-03 02:13 UTC, AlexAlexandre approved these changes
LGTM :)

2021-10-05 13:58 UTC, merged