[IMPROVE] Check permission on create team
RocketChat/Rocket.Chat.ReactNative pull request #3233
Opened 2021-06-22 18:07 UTC by reinaldonetof

## Proposed changes

* Check if the user has permission to create each one inside the `NewMessageView`: Channel, Team, Direct Message, and Discussion
* In `RoomListView`check if the user has the permissions to create, and if has at least one permission show the button to create, else don't show the button
* In `CreateChannelView` check which permission the user has: if there is permission to create a public channel, a private channel, or both.

## Issue(s)	

We're showing create team, channel, etc without checking if the user has the correct permission.
We should look for it first.

## How to test or reproduce

* In `RoomListView` check if you have any permission to create and the button will be showing
* In NewMessageView for each permission you will can see the types of rooms that you can create
* In `CreateChannelView` you will able to see if you can create a private, public channel, or both.

## Screenshots
<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</thead>
</tr>
<body>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/47038980/122976626-f11aed80-d36a-11eb-8b85-26d9b1033646.png" height="450" />
</td>
<td>
<img src="https://user-images.githubusercontent.com/47038980/122976693-098b0800-d36b-11eb-9540-a47f40119676.png"  height="450"/>
</td>
</tr>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/47038980/122976093-63d79900-d36a-11eb-8ebb-0ee63058fea4.png" height="450" />
</td>
<td>
<img src="https://user-images.githubusercontent.com/47038980/122976208-82d62b00-d36a-11eb-91f0-80629a3db449.png"  height="450"/>
</td>
</tr>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/47038980/122976777-232c4f80-d36b-11eb-9b49-c5d3ff87024e.png" height="450" />
</td>
<td>
<img src="https://user-images.githubusercontent.com/47038980/122976865-39d2a680-d36b-11eb-8300-21fb4ec2bc8b.png"  height="450"/>
</td>
</tr>
</tbody>
</table>

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2021-06-24 17:15 UTC, gerzonc approved these changes
LGTM

2021-08-06 18:21 UTC, gerzonc requested changes

2021-08-06 18:21 UTC, gerzonc commented on app/views/CreateChannelView.js
> +		this.handleHasPermission();
Can you move it to a `componentDidMount` instead?

2021-08-06 18:21 UTC, gerzonc commented on app/views/RoomsListView/index.js
> +					{isDisabledToCreateRoom ? (
Can you change this name to `canCreateRoom`? Feels more appealing

2021-08-10 19:28 UTC, gerzonc approved these changes
LGTM!

2021-08-24 16:52 UTC, gerzonc approved these changes
LGTM

2021-10-04 15:36 UTC, AlexAlexandre approved these changes
LGTM :)

2021-10-05 13:59 UTC, merged