[FIX] Dealing well with pre-configured tags
RocketChat/Rocket.Chat.ReactNative pull request #3298
Opened 2021-07-26 15:05 UTC by reinaldonetof

## Proposed changes

Users should be able to select tags and save room.

Depends on https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3294

## Issue(s)	

The UI/UX of Omnichannel tags is not good. The App must be compatible with either pre-configured tags or allow agents to set the tags they want, but currently, it seems agents just can't use it properly.

## How to test or reproduce

1 - Activate Omnicahnnel ->  https://docs.rocket.chat/guides/omnichannel-guides/omnichannel-admins-guide
2 - Go to Omnichannel Tags (Enterprise Edition)
3 - Create one or more Tags -> https://docs.rocket.chat/guides/omnichannel-guides/omnichannel-manger-guides/tags
4 - Start a new chat through Livechat
5 - Take the Chat in the queue
6 - Go to Room Information
7 - Edit Room

## Screenshots

### Before
<img height="500" alt="Screen Shot 2021-07-26 at 11 58 42" src="https://user-images.githubusercontent.com/47038980/127011228-a8721295-b5e4-4069-9e02-d96735c16145.png">

### After

https://user-images.githubusercontent.com/47038980/127012093-31b60092-e9bf-4f75-a0f3-6d47ec0aa953.mov

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2021-07-26 17:57 UTC, reinaldonetof commented on app/views/LivechatEditView.js
> +	console.log('🚀 ~ file: LivechatEditView.js ~ line 47 ~ inputs', inputs);
remove console.log

2021-08-10 19:46 UTC, gerzonc requested changes

2021-08-10 19:46 UTC, gerzonc commented on app/views/LivechatEditView.js
> +	user, navigation, route, theme, editOmnichannelContact, editLivechatRoomCustomfields
Can you add a margin between the Save button and the tags input field so it doesn't look like this?
![image](https://user-images.githubusercontent.com/36211892/128925042-8d828338-696e-4b0e-b169-a04a1d2dde29.png)

2021-08-18 13:42 UTC, gerzonc approved these changes
LGTM

2021-08-23 14:08 UTC, merged