[CHORE] Update Reanimated to 2.2.0
RocketChat/Rocket.Chat.ReactNative pull request #3341
Opened 2021-08-24 14:26 UTC by gerzonc

## Proposed changes

## Issue(s)	

## How to test or reproduce

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2021-08-31 14:29 UTC, AlexAlexandre requested changes
The code it's ok, but could you please merge the latest changes from develop into this branch ?

2021-08-31 14:40 UTC, AlexAlexandre approved these changes
LGTM

2021-09-06 19:43 UTC, diegolmello reviewed
@gerzonc don't we need these extra steps on Android? https://docs.swmansion.com/react-native-reanimated/docs/installation#android

2021-09-15 21:57 UTC, gerzonc commented
> @gerzonc don't we need these extra steps on Android? https://docs.swmansion.com/react-native-reanimated/docs/installation#android

It seems it was working fine without it, but I added it anyway just in case something didn't get to work fine with further changes we might do.

2021-09-16 18:27 UTC, diegolmello commented on app/containers/ActionSheet/ActionSheet.tsx
> +		const opacity = interpolateNode(animatedPosition.current, {
https://docs.swmansion.com/react-native-reanimated/docs/2.2.0/migration#1-interpolate-renamed-to-interpolatenode

2021-09-16 18:27 UTC, diegolmello commented on app/presentation/ImageViewer/ImageViewer.android.tsx
> +		easing: EasingNode.inOut(EasingNode.cubic)
https://docs.swmansion.com/react-native-reanimated/docs/2.2.0/migration#2-easing-renamed-to-easingnode

2021-10-01 20:34 UTC, merged