Chore: Migrate LivechatEditView to Typescript
RocketChat/Rocket.Chat.ReactNative pull request #3499
Opened 2021-11-12 00:54 UTC by reinaldonetof

## Proposed changes

Migrate LivechatEditView to Typescript, create 2 definitions used in LiveChatEditView

## Issue(s)	

## How to test or reproduce

- You should be an omnichannel agent
- Join a chat from Omnichannel's queue, then click on the header and click on the name
- You should be moved to another screen, then click on the `edit` button, on the header
- And the title's header should be `Edit`. So this is the screen.

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2021-12-01 16:39 UTC, gerzonc approved these changes
LGTM

2021-12-08 21:57 UTC, diegolmello submitted a review, later dismissed

2021-12-08 21:57 UTC, diegolmello commented on app/definition/ITagsOmnichannel.ts
> +export interface ITagsOmnichannel {
These files are creating a new folder
![image](https://user-images.githubusercontent.com/804994/145290190-443627b1-68d8-4051-b525-fe31d72a381e.png)

2021-12-08 21:57 UTC, diegolmello commented on app/definition/IVisitor.ts
> +	visitorEmails?: Array<IVisitorEmail>;
It's not wrong, but just for the sake of consistency, we should use the same you've used on the other file: `string[]`
```suggestion
	phone?: IVisitorPhone[];
	visitorEmails?: IVisitorEmail[];
```

2021-12-08 21:57 UTC, diegolmello commented on app/views/LivechatEditView.tsx
> +	route: RouteProp<any, 'LivechatEditView'>;
Missing proper stack instead of `any`

2021-12-21 16:42 UTC, gerzonc requested changes

2021-12-21 16:42 UTC, gerzonc commented on app/containers/UIKit/MultiSelect/index.tsx
> +	onClose?: Function;
Can we send how the function is composed instead of setting `Function`? I think `Function` is too ambiguous and open to anything

2021-12-21 16:42 UTC, gerzonc commented on app/definitions/IRoom.ts
> +		[key: string]: any;
Why `any`?

2021-12-21 16:42 UTC, gerzonc commented on app/views/LivechatEditView.tsx
> +	user: any;
Just adding a comment here in case that someone else sees it, but the reason why this is `any` is because it comes from `mapStateToProps`

2021-12-21 16:42 UTC, gerzonc commented on app/views/LivechatEditView.tsx
> +	[index: string]: RNTextInput | null;
```js
interface IInputsRefs {
	[index: string]: RNTextInput | null;
	name: RNTextInput | null;
	phone: RNTextInput | null;
	topic: RNTextInput | null;
}
```

For some reason I prefer `index` to be the first one always, but that's on you :)

2021-12-24 20:59 UTC, reinaldonetof commented on app/containers/TextInput.tsx
> +	inputRef?: React.Ref<RNTextInput>;
Actually, the approach to ForwardRef was weird. Now I adjusted.

https://www.carlrippon.com/react-forwardref-typescript/

2021-12-24 21:00 UTC, reinaldonetof commented on app/containers/TextInput.tsx
> +	inputRef?: React.Ref<RNTextInput>;
@AlexAlexandre can you take a look at this later? Thanks!

2021-12-27 20:24 UTC, GleidsonDaniel commented on app/containers/TextInput.tsx
> +	inputRef?: React.Ref<RNTextInput>;
@reinaldonetof Can this file sometimes not receive the ref?
If yes the type is correct.
However, if he always receives the ref, he can put React.RefObject which is nice.

2021-12-27 20:33 UTC, GleidsonDaniel approved these changes
LGTM

The solution of the refs seems to me satisfactory.

2021-12-27 20:33 UTC, GleidsonDaniel commented on app/containers/TextInput.tsx
> +	inputRef?: React.Ref<RNTextInput>;
Actually looking here your logic is correct, ignore my previous comment hahaha

2022-01-12 13:51 UTC, diegolmello requested changes

2022-01-12 13:51 UTC, diegolmello commented on app/definitions/ISubscription.ts
> +	sms?: boolean;
Isn't sms a dynamic column on Omnichannel?
If so, we shouldn't add it here.
Same for the code, as we shouldn't count on having it.

2022-01-25 16:42 UTC, GleidsonDaniel requested changes

2022-01-25 16:42 UTC, GleidsonDaniel commented on app/views/LivechatEditView.tsx
> +	const [customFields, setCustomFields] = useState({} as ICustomFields);
Why are you using it this way and not the default way?
Like that:
`const [customFields, setCustomFields] = useState<ICustomFields>({});`

2022-02-07 15:18 UTC, merged