Chore: Migrate DisplayPrefsView to TS
RocketChat/Rocket.Chat.ReactNative pull request #3555
Opened 2021-12-14 23:39 UTC by reinaldonetof

## Proposed changes

Migrate DisplayPrefsView to TS

## Issue(s)	

## How to test or reproduce

- Click on `hamburguer` icon, on the SideBar click on `Display`, then change the preferences of display and back to list of rooms to check the difference

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2021-12-21 14:51 UTC, AlexAlexandre requested changes

2021-12-21 14:51 UTC, AlexAlexandre commented on app/views/DisplayPrefsView.tsx
> +	sortBy?: 'alphabetical' | 'activity';
What do you think if we create types for sortBy and displayMode, for example: 

`type TSortBy = 'alphabetical' | 'activity';` 
`type TdisplayMode = typeof DISPLAY_MODE_EXPANDED | typeof DISPLAY_MODE_CONDENSED;`

2021-12-21 14:51 UTC, AlexAlexandre commented on app/views/DisplayPrefsView.tsx
> +interface IParam {
Are you sure about all fields is optional ? If so, we can remove all `?` and use the `Partial<IParams>`

2021-12-27 21:00 UTC, GleidsonDaniel requested changes
Apart from the shortBy issue, it's ok for me.

2021-12-28 13:05 UTC, GleidsonDaniel approved these changes

2022-01-11 14:47 UTC, merged