[IMPROVE] Add support for ephemeral messages inside threads
RocketChat/Rocket.Chat.ReactNative pull request #3687
Opened 2022-02-03 20:05 UTC by diegolmello

## Proposed changes

- Added support for sending ephemeral messages inside threads when they have `tmid`
- Added all extra info from the message payload, like user object

## Issue(s)	

## How to test or reproduce

- Send `/sendlater help` on a thread from the app
- It should receive and render the ephemeral message inside the thread (not on main room)

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-02-04 14:36 UTC, GleidsonDaniel requested changes
Another thing is that testing here, sometimes the "cat" appeared and other times only a message box, is this the expected operation? Since we are fixing the name to rocket.cat.

![Screen Shot 2022-02-04 at 11 35 32](https://user-images.githubusercontent.com/18687097/152547108-4685013f-707c-426c-a449-bcd25a173798.png)

2022-02-04 14:36 UTC, GleidsonDaniel commented on app/lib/methods/subscriptions/rooms.js
> +						username: 'rocket.cat',
A doubt, this name should be fixed?

2022-02-07 20:39 UTC, diegolmello commented
> Another thing is that testing here, sometimes the "cat" appeared and other times only a message box, is this the expected operation? Since we are fixing the name to rocket.cat.
> 
> ![Screen Shot 2022-02-04 at 11 35 32](https://user-images.githubusercontent.com/18687097/152547108-4685013f-707c-426c-a449-bcd25a173798.png)

@GleidsonDaniel I was not able to reproduce that 😕

2022-02-07 21:37 UTC, GleidsonDaniel approved these changes

2022-02-15 18:46 UTC, merged