Chore: Migrate loadMissedMessages to typescript
RocketChat/Rocket.Chat.ReactNative pull request #3704
Opened 2022-02-09 19:15 UTC by GleidsonDaniel

## Proposed changes

Migrate loadMissedMessages to typescript

## Issue(s)	

## How to test or reproduce

Enter a room and force new messages to load via refresh.

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-02-10 17:05 UTC, AlexAlexandre requested changes

2022-02-10 17:05 UTC, AlexAlexandre commented on app/lib/methods/loadMissedMessages.ts
> +				// loaderItem is null only to surpass the obligatoriness of the item in the function, as soon as it is migrated it will not be necessary.
WDYF about add an `TODO` with a `@ts-ignore`? 
I think this makes it easier not to forget to change it later

2022-02-10 21:12 UTC, AlexAlexandre approved these changes

2022-02-15 15:48 UTC, AlexAlexandre submitted a review, later dismissed

2022-02-16 14:18 UTC, GleidsonDaniel commented on app/lib/methods/loadMissedMessages.ts
> +async function load(this: IRocketChat, { rid: roomId, lastOpen }: { rid: string; lastOpen: string }) {
Tks

2022-02-16 14:18 UTC, GleidsonDaniel commented on app/lib/methods/loadMissedMessages.ts
>  			const data = await load.call(this, { rid: args.rid, lastOpen: args.lastOpen });
Tks

2022-02-16 14:22 UTC, AlexAlexandre approved these changes

2022-02-21 13:59 UTC, merged