Chore: Dehydrate share extension from rocketchat.js
RocketChat/Rocket.Chat.ReactNative pull request #3753
Opened 2022-02-17 05:54 UTC by gerzonc

## Proposed changes

## Issue(s)	

## How to test or reproduce

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-02-17 19:16 UTC, diegolmello requested changes

2022-02-17 19:16 UTC, diegolmello commented on app/lib/rocketchat/services/shareExtension.ts
> +export async function shareExtensionInit(server: string) {
- Open Photos on iOS sim
- Try to share a photo to our app
- Share extension opens, but Reactotron raises this error
<img width="724" alt="image" src="https://user-images.githubusercontent.com/804994/154553842-173d7fdf-94e8-45da-a49e-9e02407f2bcf.png">

2022-02-25 05:11 UTC, gerzonc commented on app/definitions/ICredentials.ts
> +}
Comes from `@rocket.chat/sdk`

2022-02-25 05:13 UTC, gerzonc commented on app/lib/rocketchat/services/sdk.ts
> +	}
Needed; even though is something being worked on the dehydration for `login` methods, without this `shareExtensionInit` might crash like on previous review

2022-03-02 19:57 UTC, GleidsonDaniel requested changes

2022-03-02 19:57 UTC, GleidsonDaniel commented on app/definitions/IRocketChat.ts
> +	shareSDK: any;
```suggestion
```

2022-03-02 19:57 UTC, GleidsonDaniel commented on app/lib/rocketchat/services/sdk.ts
> +	login(credentials: ICredentials) {
Use current

2022-03-02 19:57 UTC, GleidsonDaniel commented on app/lib/rocketchat/services/shareExtension.ts
> +	this.shareSDK = sdk.disconnect();
I think there are other better ways to do this implementation without using this.

2022-03-15 13:58 UTC, GleidsonDaniel approved these changes

2022-03-16 20:40 UTC, merged