Chore: Dehydrate login methods from rocketchat.js
RocketChat/Rocket.Chat.ReactNative pull request #3759
Opened 2022-02-18 15:52 UTC by gerzonc

## Proposed changes

Dehydrate login methods from `rocketchat.js`; this is part of the TypeScript migration.
## Issue(s)	

## How to test or reproduce

1. Test every login method (login with password, login with SSO, oauth, etc.)
2. Test if app reopening/disconnecting works properly
## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-03-02 14:45 UTC, GleidsonDaniel requested changes

2022-03-02 14:45 UTC, GleidsonDaniel commented on app/lib/rocketchat/services/connect.ts
> +	const sdk = new RocketchatClient({ host: server, protocol: 'ddp', useSsl: useSsl(server) });
Up there you import `sdk` and here in this function you create it with the name `sdk`, javascript can understand, but this is not a good practice.

2022-03-02 14:50 UTC, gerzonc commented on app/definitions/ILoggedUser.ts
> +	me: {
`showMessageInMainThread` and `enableMessageParserEarlyAdoption` do not exist when coming from server, so we have to call them e.g. from `settings.preferences.enableMessageParserEarlyAdoption`. But I can create another  type for this.

2022-03-02 14:52 UTC, gerzonc commented on app/definitions/IRocketChat.ts
> +	shareSDK: any;
Leftover

2022-03-02 19:29 UTC, GleidsonDaniel requested changes
Another thing is that it is missing to migrate the connect method.

2022-03-02 19:29 UTC, GleidsonDaniel commented on app/lib/rocketchat/services/sdk.ts
> +	}
I don't think it's interesting to create a wrapper for each method of this one, since they are simple methods, better to use `sdk.current`

2022-03-04 17:42 UTC, GleidsonDaniel approved these changes
Unfortunately the `this` will have to remain there, simply because they are being used in other functions outside the scope of connect.

2022-03-08 18:54 UTC, merged