Chore: Migrate REST API - getRoomInfo to Typescript
RocketChat/Rocket.Chat.ReactNative pull request #3823
Opened 2022-03-04 02:21 UTC by AlexAlexandre

## Proposed changes

## Issue(s)	

## How to test or reproduce

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-03-04 16:28 UTC, gerzonc requested changes

2022-03-04 16:28 UTC, gerzonc commented on app/definitions/IRoom.ts
> +	joinCodeRequired?: boolean;
Shouldn't be `IServerRoomItem` instead?

2022-03-04 16:28 UTC, gerzonc commented on app/views/TeamChannelsView.tsx
> +				let params = {} as Partial<IRoom>;
`IServerRoomItem` probably

2022-03-07 12:01 UTC, GleidsonDaniel approved these changes

2022-03-16 00:03 UTC, gerzonc approved these changes
LGTM

2022-03-16 00:04 UTC, merged