[NEW] Redesign quoted messages
RocketChat/Rocket.Chat.ReactNative pull request #3883
Opened 2022-03-11 19:57 UTC by gerzonc

Changes current design to match with how it looks on the Web client and fixes attachments on quoted messages

## Proposed changes

## Issue(s)	

## How to test or reproduce

## Screenshots

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-03-15 14:26 UTC, diegolmello requested changes
A couple of questions:
- We should apply use real name
- Quote time is misaligned
- Did we run Detox?
- Should we play the audio on quote or just redirect?
- Add spacing between quote and message, like on Figma
<img src="https://user-images.githubusercontent.com/804994/158399731-1a696d6f-5206-486d-a580-f78cb2725895.png" width="350" />

2022-03-15 16:05 UTC, gerzonc commented
> * We should apply use real name?
We don't receive that information on the request, just `author_name` which give us the username.

> * Did we run Detox?
Not really 🙈

> * Should we play the audio on quote or just redirect?
I think we should just redirect... I thought about playing the audio, but UX for jumping to the original message won't leave enough area for you to jump to it besides the corners.

Other questions were not responded as I assume they are just part of the review, will work on those changes.

2022-03-16 05:02 UTC, ankar84 commented
Nice to have that improvement in 4.26!

2022-03-16 21:04 UTC, diegolmello approved these changes
LGTM

2022-03-18 04:18 UTC, gerzonc commented on app/containers/message/Attachments.tsx
> +		}
This looks ugly but is the only way I could think of in order to achieve `Image` to be after `Reply` 🙈 
<img width="311" alt="image" src="https://user-images.githubusercontent.com/36211892/158936658-a5de26b2-a1ce-4ccb-a566-fac1ba2153e8.png">

2022-03-21 13:13 UTC, gerzonc commented on app/containers/message/Audio.tsx
> +						thumbImage={isIOS ? { uri: 'audio_thumb', scale } : undefined}
Can't we just add the `audio_thumb` asset to Android? I think it's better so it looks the same in both platforms

2022-03-21 20:44 UTC, merged