Chore: Migrate containers: List to Typescript
RocketChat/Rocket.Chat.ReactNative pull request #3921
Opened 2022-03-17 02:04 UTC by reinaldonetof

## Proposed changes

Migrate containers: List to Typescript

## Issue(s)	

## How to test or reproduce

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-03-17 13:07 UTC, GleidsonDaniel approved these changes

2022-03-18 03:24 UTC, AlexAlexandre requested changes

2022-03-18 03:24 UTC, AlexAlexandre commented on app/containers/List/ListItem.tsx
> +const Button = React.memo<IListButtonPress>(({ onPress, backgroundColor, underlayColor, ...props }: IListButtonPress) => (
```suggestion
const Button = React.memo(({ onPress, backgroundColor, underlayColor, ...props }: IListButtonPress) => (
```

2022-03-18 14:56 UTC, AlexAlexandre approved these changes

2022-03-25 18:09 UTC, merged