[FIX] User status update
RocketChat/Rocket.Chat.ReactNative pull request #3961
Opened 2022-03-24 18:42 UTC by gerzonc

## Proposed changes

Based on #3004
Currently we're updating the user status two times: when we tap on the user status and when we tap on `Done`. This fixes the first one, since it updates the user status even if you tap on `Cancel`
## Issue(s)	

Closes #3003
## How to test or reproduce

Test case 1

1. Go to Sidebar > Edit user status
2. Change user status / user status text
3. Tap on `Cancel`

Expected behavior: User status / user status text should be the same.

Test case 2

1. Go to Sidebar > Edit user status
2. Change user status / user status text
3. Tap on `Done`
4. 
Expected behavior: User status / user status text should be the same.

## Screenshots

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-03-28 20:51 UTC, diegolmello requested changes

2022-03-28 20:51 UTC, diegolmello commented on app/views/StatusView.tsx
> +			await this.setCustomStatus();
This is a refactor, so we should merge `submit` and `setCustomStatus`

2022-03-28 20:51 UTC, diegolmello commented on app/views/StatusView.tsx
> +			const result = await RocketChat.setUserStatus(status as UserStatus, statusText as string);
We probably don't need to cast to string there.

2022-03-28 20:51 UTC, diegolmello commented on app/views/StatusView.tsx
> +				}
Log user events.
We're looking for submit, tapped `away`, etc.

2022-03-28 20:51 UTC, diegolmello commented on app/views/StatusView.tsx
> +			}
No need to do this.
`log` is going to persist the relevant info.

2022-04-07 17:39 UTC, diegolmello requested changes
Missing update on Detox tests

2022-05-31 16:49 UTC, reinaldonetof approved these changes
LGTM

2022-05-31 16:50 UTC, merged