Chore: Migrate i18n to Typescript and fix the Left and Right actions in RoomItem
RocketChat/Rocket.Chat.ReactNative pull request #3988
Opened 2022-03-29 18:55 UTC by reinaldonetof

## Proposed changes

## Issue(s)	

## How to test or reproduce

- Check if the translations are work properly
- Go to Settings -> Language -> change between the languages

#### Test the Actions in Rooms List View
- Go to Settings -> Language -> change to `'العربية'` language, before the last one
- Back to Rooms List View, press and hold on any Room Item, then Drag to Right and Left and test the buttons

## Screenshots

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-03-31 20:55 UTC, diegolmello requested changes

2022-03-31 20:55 UTC, diegolmello commented on app/containers/List/ListItem.tsx
> +							{translateTitle ? I18n.t(title || '') : title}
I've seen this on some other places on this PR.
If the code reaches `''`, it's actually going to show to the end user an awkward message [like this](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3960).
A better way to fix this warning is:

```suggestion
							{translateTitle && title ? I18n.t(title) : title}
```

Please review your PR and change it on other places as well.

2022-03-31 20:55 UTC, diegolmello commented on app/containers/message/utils.ts
> +export const formatMessageCount = (count?: number, type?: string) => {
I'm sure this is a better approach
```suggestion
export const formatMessageCount = (count?: number, type?: string): string | null => {
```

2022-03-31 20:55 UTC, diegolmello commented on app/i18n/index.ts
> +	// @ts-ignore
```suggestion
	// @ts-ignore TODO: we need to review this logic
```

2022-03-31 20:55 UTC, diegolmello commented on app/views/DiscussionsView/index.tsx
> -			headerTitleContainerStyle: {
Same as the image style.
Please stop removing stuff like this.

2022-03-31 22:28 UTC, GleidsonDaniel commented
Adding one more comment to what @diegolmello  said.
If the migration is about i18n, I don't think it's ideal to change things that are unrelated to i18n, even if they look wrong. Better would be to create a task to change this in the future.

PR consistency is very important for tracking.

2022-04-11 17:56 UTC, GleidsonDaniel requested changes
The i18 part is ok, but as we said, it will remove the part that changes other things and open another PR with these changes.

2022-04-11 22:31 UTC, reinaldonetof commented
> The i18 part is ok, but as we said, it will remove the part that changes other things and open another PR with these changes.

Hey, @GleidsonDaniel I created a new function called `isTranslated` to be a function to test if the string to translate exists. Also, I could merge the develop here and deleted the files from

2022-04-12 12:08 UTC, GleidsonDaniel approved these changes

2022-04-14 20:30 UTC, merged