Chore/evaluate rocketchat v2
RocketChat/Rocket.Chat.ReactNative pull request #4035
Opened 2022-04-07 18:30 UTC by GleidsonDaniel

## Proposed changes

## Issue(s)	

## How to test or reproduce

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-04-12 14:14 UTC, diegolmello requested changes
At this point we agreed to switch to `Services.service`.
In the future, we're going to migrate to a custom hook instead.

2022-04-12 14:14 UTC, diegolmello commented on app/views/CreateDiscussionView/index.tsx
> +						name: getRoomTitle(result),
I couldn't get the reason, but we can't create discussions on this PR.

2022-04-12 17:40 UTC, GleidsonDaniel commented on app/lib/methods/triggerActions.ts
> +export async function triggerSubmitView({ viewId, ...options }: ITriggerSubmitView) {
In the end they call triggerAction and this function doesn't use this.

2022-04-12 17:47 UTC, GleidsonDaniel commented on app/lib/methods/helpers.ts
> -			this.roomsSub = await subscribeRoomsTmp.call(this);
This function has been moved to another file.

2022-04-13 13:10 UTC, GleidsonDaniel commented on app/lib/methods/index.ts
> +// export * from './getRoom'; only used inside methods folder
More or less, their signature is different, one returns throw and another null, the code will change to unite them, I think it's better to do this in another task.

2022-04-13 13:11 UTC, GleidsonDaniel commented on app/lib/methods/getSingleMessage.ts
> +const getMessage = (messageId: string): Promise<IMessage> =>
I think we should create a task to clean up redundant stuff and the like.

2022-04-13 13:12 UTC, GleidsonDaniel commented on app/lib/methods/getRoomInfo.ts
> +const getInfo = async (rid: string): Promise<IRoomInfoResult | null> => {
Just changed the file.

2022-04-14 20:03 UTC, diegolmello approved these changes

2022-04-28 20:37 UTC, merged