[FIX] Solving the navigation issue from threads on tablets
RocketChat/Rocket.Chat.ReactNative pull request #4038
Opened 2022-04-08 01:22 UTC by samay-kothari

## Proposed changes

When navigating from a thread in a room to a different room directly using the side pane on tablet was not unsubscribing the current room. This fix makes sure that the user is not subscribed to more than one room at a single time. It removes the extra room from the room redux component.
## Issue(s)	

Closes #3969 
## How to test or reproduce

## Screenshots

https://user-images.githubusercontent.com/55805094/162345029-6961b8dd-26d5-4f25-ab15-e92140c2b010.mov

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-04-16 09:27 UTC, samay-kothari commented
Hi @gerzonc,
Can you review this?

2022-04-27 13:28 UTC, gerzonc requested changes

2022-04-27 13:28 UTC, gerzonc commented on app/lib/methods/subscriptions/room.ts
> +		}
If this solves a problem only for tablets then it should be wrapped around an if validation that checks the current device platform (e.g. `if (isTablet)`). We already count with `isTablet`, `isAndroid` and `isiOS`

2022-04-28 19:02 UTC, gerzonc approved these changes
LGTM

2022-06-08 05:25 UTC, ankar84 commented
@gerzonc @diegolmello @GleidsonDaniel hey!
Is there a plans to land that fix to next release?
Thanks!

2022-09-28 10:57 UTC, ankar84 commented
Any news?

2022-09-28 11:53 UTC, diegolmello commented
@ankar84 This is not the _best_ way to fix it, so I need to try another way.
For example, disabling nested rooms (Room A opening Room B) would solve this by default.

2022-09-28 13:15 UTC, ankar84 commented
> @ankar84 This is not the _best_ way to fix it, so I need to try another way. For example, disabling nested rooms (Room A opening Room B) would solve this by default.

ok. I get it. Waiting for a proper fix then.
Thank you, Diego!

2022-11-25 13:22 UTC, closed without merging