Chore: Migrate containers/Toast functional component and hooks
RocketChat/Rocket.Chat.ReactNative pull request #4128
Opened 2022-04-27 21:15 UTC by samay-kothari

## Proposed changes

## Issue(s)	

## How to test or reproduce

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-04-27 21:16 UTC, samay-kothari commented
@gerzonc Please have a look

2022-04-27 21:45 UTC, gerzonc requested changes

2022-04-27 21:45 UTC, gerzonc commented on app/containers/Toast.tsx
> +	let listner: Function;
```suggestion
	let listener: Function;
```

2022-04-27 21:45 UTC, gerzonc commented on app/containers/Toast.tsx
> +		listner = EventEmitter.addEventListener(LISTENER, showToast);
```suggestion
		listener = EventEmitter.addEventListener(LISTENER, showToast);
```

2022-04-27 21:45 UTC, gerzonc commented on app/containers/Toast.tsx
> +const Toast = ({ theme }: IToastProps) => {
If you remove the `withTheme` HOC and use the `useTheme` hook you won't need this, you could use `colors`
```ts
const { colors } = useTheme();
```

2022-04-27 21:45 UTC, gerzonc commented on app/containers/Toast.tsx
> +			style={[styles.toast, { backgroundColor: themes[theme!].toastBackground }]}
By using `colors` from the `useTheme` hook, you can change `themes[theme!].toastBackground` with `colors.toastBackground`

2022-04-27 21:45 UTC, gerzonc commented on app/containers/Toast.tsx
> +			textStyle={[styles.text, { color: themes[theme!].buttonText }]}
Same here

2022-04-27 21:45 UTC, gerzonc commented on app/containers/Toast.tsx
>  	theme?: TSupportedThemes;
Won't be needed anymore

2022-04-28 05:01 UTC, samay-kothari commented
@gerzonc I have made the requested changes, please review.

2022-04-28 14:27 UTC, samay-kothari commented
https://user-images.githubusercontent.com/55805094/165775320-e11f4acd-b0df-4c1f-abc4-8af69bae31a6.mp4

Working as expected after migration

2022-04-28 18:57 UTC, gerzonc approved these changes
LGTM

2022-05-20 20:56 UTC, GleidsonDaniel commented
Some points:
When using the ref and listener as let you will cause numerous re-renders, as it will always be initialized again with each render.
Another thing is about this useEffect without [ ], you really want it to run every re-render, shouldn't you just initialize it once?

2022-06-20 19:20 UTC, closed without merging