[NEW] Go to RoomView if the mentioned #channel is already joined
RocketChat/Rocket.Chat.ReactNative pull request #4204
Opened 2022-05-18 06:35 UTC by try-catch-stack

## Proposed changes

## Issue(s)	

Fixes #4201 
## How to test or reproduce

* Mention a `#channel` that you haven't joined and click on it. You should be redirected to `RoomInfoView`  .
* Mention a `#channel` that you have already joined and click on it. You should be redirected to the `RoomView` directly.

## Screenshots

Uploading new.channel-redirect.mp4…

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [X] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-05-20 19:44 UTC, diegolmello requested changes

2022-05-24 21:33 UTC, diegolmello requested changes

2022-05-24 21:33 UTC, diegolmello commented on app/containers/markdown/Hashtag.tsx
> +				} else navigation.push('RoomView', room);
```suggestion
				if (isMasterDetail) {
					// Close the modal if it is open and then redirect to the channel
					Navigation.navigate('DrawerNavigator');
					navigation.replace('RoomView', room);
				} else {
				    navigation.push('RoomView', room);
				}}
```

2022-05-24 21:33 UTC, diegolmello commented on app/containers/markdown/Hashtag.tsx
> +				navToRoomInfo(navParam);
Did you notice on your video the title is getting blank on this step?
Also, try to interact a bit more on this, like joining, navigating to RoomActions, etc and make sure the layout is working correctly.

2022-05-24 21:33 UTC, diegolmello commented on app/containers/markdown/Hashtag.tsx
> +			const room = await getSubscriptionByRoomId(navParam.rid!);
Try not to use non-null assertion (bang).
It's bad and might crash the app in production.
if necessary, do `if (navParam.rid) { ... }`

2022-05-24 21:33 UTC, diegolmello commented on app/containers/markdown/Hashtag.tsx
> +					navigation.replace('RoomView', room);
Maybe you should use `goRoom`.
It's going to be hard to maintain this in case we change `goRoom` logic.

2022-05-30 16:27 UTC, GleidsonDaniel commented
@try-catch-stack can you fix the tests?

2022-05-30 16:35 UTC, try-catch-stack commented
Hey @GleidsonDaniel . I discussed this issue with @diegolmello on the channel. I tried few mocks for the libraries but didn't work so left it as it is for now. A point to be mentioned is, when I didn't use the `goRoom` method, the tests were fine.
Maybe some insights would help (:

2022-05-30 16:41 UTC, GleidsonDaniel commented
Okay, I'll take a look and try to help you,

2022-06-02 19:37 UTC, GleidsonDaniel commented
Done bro :)

2022-06-02 19:38 UTC, try-catch-stack commented
Woah 🙇🏼 !! Thanks @GleidsonDaniel  :)

2022-06-10 20:31 UTC, GleidsonDaniel approved these changes

2022-06-10 20:33 UTC, merged