Chore: Migrate LoginServices to Hooks
RocketChat/Rocket.Chat.ReactNative pull request #4216
Opened 2022-05-25 03:10 UTC by reinaldonetof

## Proposed changes

## Issue(s)	

## How to test or reproduce

- Join into `open.rocket.chat`
- Go to Login screen and test the oauth's buttons, `more options` and login with email too

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-05-25 14:11 UTC, diegolmello requested changes

2022-05-25 14:11 UTC, diegolmello commented on app/containers/LoginServices.tsx
> +	const onPressFacebook = () => {
On our refinement, we talked about extracting all these service logic functions away from the component.

2022-05-25 14:11 UTC, diegolmello commented on app/containers/LoginServices.tsx
> +	const renderServicesSeparator = () => {
You don't want to use `renderSomething`.
That's ok for class components, but not for function components, as it's going to get recreated on every render.
The ideal fix is to extract the logic to its own component `<ServicesSeparator />` and send the necessary props.

A _not-so-valid_ fix would be to use `useCallback`, but it's hard to maintain and it's kind of anti-pattern.
There are use cases for this, but 99% of times a separate component is the right way.

2022-05-25 14:11 UTC, diegolmello commented on app/containers/LoginServices.tsx
> +		if (length > 0 && Accounts_ShowFormLogin) {
I didn't get this change.

2022-06-01 20:51 UTC, diegolmello requested changes

2022-06-01 20:51 UTC, diegolmello commented on app/containers/LoginServices/index.tsx
> +			))}
This is wrong.
`ServicesList` should be the whole map and render a `Service` component (called `ServiceList` now).

```tsx
// index.tsx
<ServicesList services={services} />

// ServicesList.tsx
{Object.values(services).map((service: IItemService) => (
	<Service
		CAS_enabled={CAS_enabled}
		CAS_login_url={CAS_login_url}
		Gitlab_URL={Gitlab_URL}
		server={server}
		service={service}
	/>
))}
```

2022-06-01 20:51 UTC, diegolmello commented on app/containers/LoginServices/index.tsx
> +				onPressButtonSeparator={onPressButtonSeparator}
No need to name it using the context.

```suggestion
				onPress={onPressButtonSeparator}
```

2022-06-01 20:51 UTC, diegolmello commented on app/containers/LoginServices/interfaces.ts
> +	authType: string;
You know the available types.
We could benefit from having them defined here.

```suggestion
	authType: 'facebook' | 'github' | ...;
```

2022-06-01 20:51 UTC, diegolmello commented on app/containers/LoginServices/serviceLogin.ts
> +const LOGIN_STYPE_REDIRECT = 'redirect';
Unify into TLoginStyle

2022-06-01 20:51 UTC, diegolmello commented on app/containers/LoginServices/serviceLogin.ts
> +		loginStyle: string;
Apply TLoginStyle

2022-06-01 20:51 UTC, diegolmello commented on app/containers/LoginServices/index.tsx
> +				<ServicesList
You might need to add `key` to prevent re-renders

2022-06-06 20:15 UTC, GleidsonDaniel requested changes

2022-06-06 20:15 UTC, GleidsonDaniel commented on app/containers/LoginServices/Service.tsx
> +		let onPress: any = () => {};
Will this value be changed?
Why is it not recommended to use let inside components, as you have no reference to which value that is, which causes some re-rendering.
Same buttonText

2022-06-13 20:37 UTC, GleidsonDaniel approved these changes

2022-06-23 12:56 UTC, merged