Chore: Migration to Hooks - FormTextInput
RocketChat/Rocket.Chat.ReactNative pull request #4256
Opened 2022-05-30 19:26 UTC by AlexAlexandre

## Proposed changes

## Issue(s)	

## How to test or reproduce

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-05-31 20:49 UTC, diegolmello requested changes
Left a few comments, but you should actually wait for https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4195 so you prevent rework.

2022-05-31 20:49 UTC, diegolmello commented on app/containers/TextInput/FormTextInput.tsx
> +		const { colors, theme } = useTheme();
Stop using theme here.
Use it on TextInput/index directly.

2022-05-31 20:49 UTC, diegolmello commented on app/containers/TextInput/FormTextInput.tsx
> +const FormTextInput = React.memo(
This memo isn't doing anything.
TextInput doesn't handle its own state, so it receives props all the time, which is going to trigger re-renders anyway.
Even if it wasn't the case, it receives non-primitive values which also would trigger re-renders.

2022-05-31 20:49 UTC, diegolmello commented on app/containers/TextInput/FormTextInput.tsx
> +		const showIconRight = () =>
You should prevent the usage of this kind of function creation inside function components.
You're only recreating something that React can't really understand.
On this case, it's actually easy to just abstract and reuse it inside the return.

2022-05-31 20:49 UTC, diegolmello commented on app/containers/TextInput/FormTextInput.tsx
> +		const showLoading = () => (
Similar to the icons. There's no reason to return a function here.
```jsx
{loading ? <ActivityIndicator ... /> : null}
```

2022-06-07 13:11 UTC, GleidsonDaniel commented on app/containers/TextInput/TextInput.tsx
> +// export default ThemedTextInput;
👀

2022-06-07 13:12 UTC, GleidsonDaniel approved these changes

2022-06-27 18:46 UTC, merged