Chore: Migrate NotificationPreferencesView to hooks
RocketChat/Rocket.Chat.ReactNative pull request #4327
Opened 2022-06-28 15:34 UTC by GleidsonDaniel

## Proposed changes

Migrate NotificationPreferencesView to hooks and improves layout and user feedback 
- It is no longer necessary to change screens to select some options, they are via actionSheet.
- Now when an error occurs when changing the option, it reverts to the old option.

## Issue(s)	

## How to test or reproduce

- Try changing some option and see if it will actually replicate on the web or in tests.
- Force an error (too many requests for example) and see the error message and the go back option.

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-07-18 20:50 UTC, diegolmello submitted a review, later dismissed

2022-07-18 20:50 UTC, diegolmello commented on app/containers/ActionSheet/Item.tsx
> +/* eslint-disable no-nested-ternary */
I don't think this is needed.

2022-07-18 20:50 UTC, diegolmello commented on app/containers/ActionSheet/styles.ts
> +	none: { width: 20 }
You're not using it

2022-07-18 20:50 UTC, diegolmello commented on app/views/NotificationPreferencesView/index.tsx
> +const RenderListPicker = React.memo(
`room` is an object and `onChangeValue` is a function, so React.memo isn't really doing anything.

2022-07-18 20:50 UTC, diegolmello commented on app/views/NotificationPreferencesView/index.tsx
> +			showErrorAlertWithEMessage(e);
This is confusing.
When is it calling `onError`?
Will it do both `onError` and `showErrorAlertWithEMessage`?

2022-07-18 20:50 UTC, diegolmello commented on app/views/NotificationPreferencesView/index.tsx
> +				setSwitchValue(value);
Should we call `setSwitchValue` twice?

2022-07-18 20:50 UTC, diegolmello commented on app/views/NotificationPreferencesView/index.tsx
> +	preference: string;
I think we could actually type this.
This preference is an abstraction of both `OPTIONS` or `IRoomNotifications`.

For the first one, you could
- use `keyof typeof OPTIONS`
- remove [this nonsense](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/60f781d20e24ca92f9cd2c5dd9ef41de16fd0767/app/views/NotificationPreferencesView/options.ts#L7)
- remove the assertion `as IOptionsField` 
- Everything `RenderListPicker` is going to be inferred

Apply something like that to `IRoomNotifications` and we're good.

2022-07-22 21:40 UTC, reinaldonetof requested changes

2022-07-22 21:40 UTC, reinaldonetof commented on app/views/NotificationPreferencesView/index.tsx
> +				onChangeValue(preference, { [preference]: switchValue ? '1' : '0' }, () => setSwitchValue(switchValue));
WDYT to use named params?

2022-07-22 21:40 UTC, reinaldonetof commented on app/views/NotificationPreferencesView/index.tsx
> +	const rid = route.params?.rid ?? '';
Is this really needed? Is there any possibility the rid be undefined?

2022-07-25 16:39 UTC, GleidsonDaniel commented on app/views/NotificationPreferencesView/index.tsx
> +				onChangeValue(preference, { [preference]: switchValue ? '1' : '0' }, () => setSwitchValue(switchValue));
named params?

2022-07-25 19:09 UTC, reinaldonetof approved these changes

2022-08-01 16:35 UTC, merged