[FIX] Markdown's ListItem not using the entered index
RocketChat/Rocket.Chat.ReactNative pull request #4388
Opened 2022-07-25 18:10 UTC by GleidsonDaniel

## Proposed changes

Use the correct number instead of index.
Improvement in the code in general.

## Issue(s)	

## How to test or reproduce

Send a message like these to someone:
```
1. Test
2. Test
3. Test
```

## Screenshots
Before:
![Screen Shot 2022-07-25 at 15 06 17](https://user-images.githubusercontent.com/18687097/180845188-151c12b3-b844-44ed-a0a9-09e2ca49705c.png)

After:
![Screen Shot 2022-07-25 at 15 05 25](https://user-images.githubusercontent.com/18687097/180845150-2ded1ce7-02a7-444d-b732-7257c244e128.png)

Web:
![Screen Shot 2022-07-25 at 15 06 28](https://user-images.githubusercontent.com/18687097/180845209-d3aac700-d6e0-4b2a-80bf-1d43b982da33.png)

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [X] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-07-26 00:49 UTC, reinaldonetof requested changes
https://user-images.githubusercontent.com/47038980/180898455-192d4c29-ff7c-4441-914b-f70b575013ce.mov

Do you think is it possible to correct show the list from `markdown/List.tsx` exactly the same as OrderedList? Because it's showing a strange UI/UX, showing first ordered, later when is sent the message, turns to 1. 1. 1.

![Screen Shot 2022-07-25 at 21 49 09](https://user-images.githubusercontent.com/47038980/180899048-c3b038f6-9f03-4a4e-8a5b-3906cdbc914c.png)

See how it's showing when some error occurred.

2022-07-27 16:36 UTC, GleidsonDaniel commented
> Screen.Recording.2022-07-25.at.21.42.59.mov 
> Do you think is it possible to correct show the list from `markdown/List.tsx` exactly the same as OrderedList? Because it's showing a strange UI/UX, showing first ordered, later when is sent the message, turns to 1. 1. 1.
> 
> ![Screen Shot 2022-07-25 at 21 49 09](https://user-images.githubusercontent.com/47038980/180899048-c3b038f6-9f03-4a4e-8a5b-3906cdbc914c.png)
> 
> See how it's showing when some error occurred.

This is a parse problem and as it will be replaced in a short time, besides being a temporary visual problem (1 second), it's not worth the effort to try to solve it.

2022-08-01 19:58 UTC, diegolmello approved these changes

2022-08-11 14:30 UTC, merged

2022-09-12 12:20 UTC, sandrotanner commented
Very cool, thanks a lot!