[FIX] Can't upload the same file on two rooms at the same time
RocketChat/Rocket.Chat.ReactNative pull request #4528
Opened 2022-09-14 17:55 UTC by GleidsonDaniel

## Proposed changes

- Adds the file upload limiter (It is no longer possible to upload the file while the other one is being uploaded)
- Solves the problem of sending the same files in different rooms.
- Adjust the style to look like other spacing in the app

## Issue(s)	

## How to test or reproduce

- Try to upload a file and while it is being uploaded try uploading again.
- Send the same file into diferente channels.

## Screenshots

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-09-15 17:29 UTC, reinaldonetof approved these changes

2022-11-04 13:15 UTC, diegolmello requested changes

2022-11-04 13:15 UTC, diegolmello commented on app/i18n/locales/en.json
> +  "Error_on_upload_archive": "Error on upload archive",
This might be a false cognate or only feel wrong.
It should be `Error on file upload`
Did you search for this on the main repo?

2022-11-04 13:15 UTC, diegolmello commented on app/lib/methods/sendFileMessage.ts
> +	const uploadPath = `${path}-${rid}`;
You're using this `path-rid` pattern everywhere.
Can you reuse it?

2022-11-04 13:15 UTC, diegolmello commented on app/lib/methods/sendFileMessage.ts
> +	if (item._raw) {
You should _never_ use `_raw` directly.
It starts with an underscore for a reason.

2022-11-04 13:15 UTC, diegolmello commented on app/lib/methods/sendFileMessage.ts
> +				if (uploadRecord?._raw?.id) {
Same.

2022-11-04 13:15 UTC, diegolmello commented on app/views/RoomView/UploadProgress.tsx
> +					index !== 0 ? { marginTop: 2 } : {},
Can you explain why you're changing the visual of a logic bug?
And why you're not using multiples of 4?

2022-11-21 15:43 UTC, diegolmello approved these changes

2022-12-05 16:31 UTC, merged