[FIX] Cannot read property 'fetch' of undefined on ThreadMessagesView
RocketChat/Rocket.Chat.ReactNative pull request #4557
Opened 2022-09-23 23:31 UTC by reinaldonetof

## Proposed changes

The subscription is set the initial value as `{ }` into state [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/e883795c5fa27225d993770d5c9ca9aad0a09b0f/app/views/ThreadMessagesView/index.tsx#L84). Then we are testing the [value of subscription](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/e883795c5fa27225d993770d5c9ca9aad0a09b0f/app/views/ThreadMessagesView/index.tsx#L240) and will always be false the conditional, because it's an object.

## Issue(s)	

## How to test or reproduce

## Screenshots

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-09-28 11:58 UTC, GleidsonDaniel approved these changes

2022-11-04 13:22 UTC, diegolmello requested changes

2022-11-04 13:22 UTC, diegolmello commented on app/views/ThreadMessagesView/index.tsx
> +		if (!subscription._raw) {
Same as the other PRs.
You should have a better way to test this without looking for WM internals.

2022-11-04 13:22 UTC, diegolmello commented on e2e/tests/assorted/09-joinfromdirectory.spec.ts
> +		it('should navigate to messages thread view', async () => {
Would this crash?
I don't understand what we're testing here.

2022-11-21 15:52 UTC, diegolmello approved these changes

2022-12-02 17:06 UTC, merged