[NEW] Video conf message block
RocketChat/Rocket.Chat.ReactNative pull request #4619
Opened 2022-10-18 19:30 UTC by GleidsonDaniel

## Proposed changes

Adds support for new video conf block.

## Issue(s)	

## How to test or reproduce

Test entering and exiting a video conf using the new block.

## Screenshots
![Screen Shot 2022-10-18 at 16 29 28](https://user-images.githubusercontent.com/18687097/196525990-8b416655-0368-441a-a8bd-c362a761f155.png)
![Screen Shot 2022-10-18 at 16 29 38](https://user-images.githubusercontent.com/18687097/196526007-a1db3f93-d9b1-47d8-a8b3-bfae44f8f9e7.png)
![Screen Shot 2022-10-18 at 16 29 42](https://user-images.githubusercontent.com/18687097/196526013-087e81fd-e60d-4267-a849-6971237bc47a.png)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-11-22 20:16 UTC, diegolmello requested changes
Task's description:
```
Should not be possible to:
- Edit message
- Quote
- Pin
- Star
- Reply in DM?
```

It looks like we didn't implement that.

2022-11-22 20:16 UTC, diegolmello commented on app/containers/UIKit/VideoConferenceBlock/components/styles.ts
> +export default function useStyle() {
Pretty cool :)

2022-11-22 20:16 UTC, diegolmello commented on app/containers/UIKit/VideoConferenceBlock/components/styles.ts
> +		container: { height: 108, flex: 1, borderWidth: 1, borderRadius: 2, marginTop: 8, borderColor: colors.conferenceCallBorder },
Recently we increased most of the borderRadius to 4.
We can confirm with design team, but I think Figma might be outdated and we need to use 4 here already and on some other places below

2022-11-23 12:38 UTC, GleidsonDaniel commented on app/containers/CustomIcon/mappedIcons.js
> -	'lamp-bulb': 59812,
Man, I didn't remove anything, probably it wasn't updated so the drive file with that icon.
The only thing I did was get the drive file and add the icon I wanted.

2022-11-23 13:06 UTC, diegolmello commented on app/containers/CustomIcon/mappedIcons.js
> -	'lamp-bulb': 59812,
Can you add lamp-bulb then?

2022-11-23 13:34 UTC, diegolmello approved these changes

2022-11-24 11:37 UTC, merged

2022-11-25 04:32 UTC, ankar84 commented
@GleidsonDaniel @diegolmello 
Testing Rocket.Chat Experimental version 4.33.0.38311 (with that PR merged) on 4.8.6 server and have a feedback.
1. Enter second Jitsi call in different chat lead to black screen, so https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/4628 not fixed by this PR unfortunately
2. Ghost participant is remain on mobile when you leave and rejoin same call in same chat (that ghost users not persist on web version of Jitsi call, so it is only bug of Jitsi SDK on mobile)

2022-11-25 04:54 UTC, ankar84 commented
Tested same mobile version on 5.3.2 server version and have same issue.
Important moment - second call in different chat works fine until someone come to that call and after that screen become black.
Actually current call become real call only after 2 or more participants join it, so black screen appears on real call start.

2022-11-28 04:53 UTC, S3xyGod commented
I got the same error with @ankar84. When I initiate a call from device 1 to device 2 or web to device 2. Device 2 joins, it works. Then I ended the call from all devices and made a new call to device 2. When device 2 pressed join only black screen on device 2 but on device 1 still see device 1 already participation. Pressing the back button on device 2 will return to the previous screen, but on device 1, device 2 is still visible in the call and cannot join another call. Only when force closing the application or restarting the device will this stop and the above error will repeat with the 2nd call
![Screenshot_1669609936](https://user-images.githubusercontent.com/67996964/204196672-a01a8d9f-7cd7-451f-94ef-3061f27a864a.png)