[TEMP] Disable jitsi native module on android
RocketChat/Rocket.Chat.ReactNative pull request #4708
Opened 2022-11-25 11:08 UTC by GleidsonDaniel

## Proposed changes

Instead of running the Jitsi module via the native module, let's run it via the webview.

## Issue(s)	

## How to test or reproduce

Join and leave a call using an android device.

## Screenshots

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2022-11-28 22:12 UTC, diegolmello requested changes

2022-11-28 22:12 UTC, diegolmello commented on app/views/JitsiMeetView.android.tsx
> +				openAppWithData(JITSI_INTENT, route.params?.url);
Isn't possible to use this? https://reactnative.dev/docs/linking#sendintent-android

2022-11-29 20:47 UTC, diegolmello approved these changes

2022-11-30 14:27 UTC, diegolmello requested changes

2022-11-30 14:27 UTC, diegolmello commented on android/app/src/main/AndroidManifest.xml
> +    <queries>
Remove `android:host` pointing to Jitsi above on this file to test if it fixes the crash

2022-12-01 02:08 UTC, ankar84 commented
I tested:
- Call in Jitsi Meet app
- Deleted Jitsi Meet app and test WebView
- Few calls in a row in different chats
- ScreenSharing from PC
- Rotate smartphone during call
- mute/unmute, turn and off camera

And all tests was successful!
So, that improvement is looks good to me!
One thing - on call start a white screen appears on smartphone for 5-10 seconds (like loading of call). But maybe it's related to our Jitsi deployment.

2022-12-01 17:19 UTC, diegolmello approved these changes

2022-12-01 17:20 UTC, merged