Chore: Remove deprecated typing stream
RocketChat/Rocket.Chat.ReactNative pull request #4888
Opened 2023-02-02 21:49 UTC by diegolmello

## Proposed changes

Just drops support to `${rid}/typing` for servers above 4.0.0.
This PR doesn't implement the full compatibility for `${rid}/user-activity`, so support to threads, uploading and recording is still missing.

## Issue(s)	

## How to test or reproduce

- Typing should be working properly on servers before and after 4.0

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2023-02-02 22:20 UTC, reinaldonetof requested changes
This PR will be closed [NEW] Add recording, uploading activity indicators - https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3243 ?

2023-02-02 22:20 UTC, reinaldonetof commented on app/lib/methods/subscriptions/room.ts
> +			const [name, activity] = ddpMessage.fields.args;
considering that activity is an array of activities, what do you think about `activities`?

2023-02-03 16:06 UTC, reinaldonetof approved these changes

2023-02-14 16:38 UTC, GleidsonDaniel approved these changes

2023-02-14 18:49 UTC, merged