chore: migrate ForwardLivechatView to hooks
RocketChat/Rocket.Chat.ReactNative pull request #5002
Opened 2023-03-29 12:09 UTC by GleidsonDaniel

## Proposed changes

## Issue(s)	

## How to test or reproduce

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2023-04-17 20:32 UTC, reinaldonetof requested changes

2023-04-17 20:32 UTC, reinaldonetof commented on app/views/PickerView.tsx
> +const Item = React.memo(({ item, selected, onItemPress }: IItem) => {
We don't need this React.memo because the item is an object and onItemPress is a function

2023-04-28 20:25 UTC, reinaldonetof approved these changes

2023-05-03 16:56 UTC, diegolmello requested changes

2023-06-30 14:01 UTC, merged