fix: Change useSnaps logic to be based on component size
RocketChat/Rocket.Chat.ReactNative pull request #5032
Opened 2023-04-13 20:14 UTC by GleidsonDaniel

## Proposed changes

Change the logic of useSnaps hook to be according to component size and not on percentage

- Tested on Android and iOS devices and tablets

## Issue(s)	

resolves #5029

## How to test or reproduce

## Screenshots
<details>
      <summary>Before</summary>
      
![Simulator Screen Shot - iPad (10th generation) - 2023-04-13 at 16 52 16](https://user-images.githubusercontent.com/18687097/231871980-18d3d62a-ece8-41c4-9cd7-d1d3610c3a97.png)
![Screenshot 2023-04-13 at 16 46 50](https://user-images.githubusercontent.com/18687097/231871993-1e3b8c45-0b12-4be9-bc05-ec4c540d802c.png)
![Screenshot 2023-04-13 at 16 48 01](https://user-images.githubusercontent.com/18687097/231871998-22e6dd25-1d6b-4099-a42e-50a49fac7616.png)
![Simulator Screen Shot - iPad (10th generation) - 2023-04-13 at 16 52 49](https://user-images.githubusercontent.com/18687097/231872002-6081dcc9-a048-4a93-8f24-b529f6be655e.png)
![Screenshot 2023-04-13 at 16 50 49](https://user-images.githubusercontent.com/18687097/231872007-3aa4c4a8-9293-40c6-b7d7-b224605db048.png)
![Screenshot 2023-04-13 at 16 51 06](https://user-images.githubusercontent.com/18687097/231872011-4a859a6d-7967-4751-b297-99e452dafdb7.png)

</details>

<details>
      <summary>After</summary>
      
![Screenshot 2023-04-13 at 16 45 14](https://user-images.githubusercontent.com/18687097/231872132-f13fc5e6-b8fb-4b0a-a585-5a0daafba34e.png)
![Screenshot 2023-04-13 at 16 47 16](https://user-images.githubusercontent.com/18687097/231872138-caf673a6-6393-44cd-ac2a-112afb47ae60.png)
![Simulator Screen Shot - iPad (10th generation) - 2023-04-13 at 16 52 31](https://user-images.githubusercontent.com/18687097/231872144-0006702a-e2b1-4513-b460-292212d2882a.png)
![Simulator Screen Shot - iPhone 14 - 2023-04-13 at 16 56 13](https://user-images.githubusercontent.com/18687097/231872147-ef6bc5f7-b41b-4d28-b49b-704b39cbdc46.png)
![Screenshot 2023-04-13 at 11 34 52](https://user-images.githubusercontent.com/18687097/231872155-3105e06e-7f55-46a3-bad0-81c9cd86f9d8.png)
![Simulator Screen Shot - iPhone 14 - 2023-04-13 at 16 56 26](https://user-images.githubusercontent.com/18687097/231872157-cbd5f6a9-65a0-4763-8f9a-80c9e3abb916.png)
![Simulator Screen Shot - iPad (10th generation) - 2023-04-13 at 16 52 41](https://user-images.githubusercontent.com/18687097/231872161-f0ffa998-b29a-4317-9c5c-86257ed4c6a5.png)
![Screenshot 2023-04-13 at 16 46 02](https://user-images.githubusercontent.com/18687097/231872165-97331587-d7f2-458f-87e4-2893de759261.png)
![Screenshot 2023-04-13 at 16 47 39](https://user-images.githubusercontent.com/18687097/231872169-36689409-f169-4248-b1a5-a4da41a522b5.png)
![Screenshot 2023-04-13 at 16 49 58](https://user-images.githubusercontent.com/18687097/231872173-64585dd3-8d1f-41c2-8fd8-842d2ace1219.png)

</details>

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

Jira: []

2023-04-16 05:18 UTC, ankar84 commented
Waiting that PR to be merged!

2023-04-16 05:19 UTC, ankar84 commented
We can't release our android versions with call bug that fixed by that PR

2023-04-18 22:07 UTC, reinaldonetof requested changes

2023-04-19 21:50 UTC, GleidsonDaniel commented on app/lib/hooks/useVideoConf.tsx
> +	const snaps = useSnaps(404);
The component is 404 px

2023-04-21 08:21 UTC, arpsyapathy commented
We are waiting this PR too. Cant build apps.

2023-05-04 17:45 UTC, reinaldonetof approved these changes

2023-05-19 17:40 UTC, merged

2023-05-31 11:35 UTC, marceloschmidt commented
@diegolmello what version is this merged into?

2023-05-31 13:19 UTC, diegolmello commented
@marceloschmidt 4.39.0. It's not released yet.

2023-06-21 03:53 UTC, ankar84 commented
Tested - looks good! Thank you, team!!!