chore: migrate AuthenticationWebView to hooks
RocketChat/Rocket.Chat.ReactNative pull request #5054
Opened 2023-05-02 22:03 UTC by reinaldonetof

## Proposed changes

migrate AuthenticationWebView to hooks

## Issue(s)	

## How to test or reproduce

- Try to login using Iframe, Saml, SSL

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Documentation update (if none of the other choices apply)

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [X] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

[NATIVE-7]

2023-05-02 23:03 UTC, reinaldonetof commented on app/views/AuthenticationWebView.tsx
> +		{ leading: true }
https://css-tricks.com/debouncing-throttling-explained-examples/#aa-leading-edge-or-immediate

2023-05-03 13:27 UTC, GleidsonDaniel requested changes

2023-05-03 13:27 UTC, GleidsonDaniel commented on app/views/AuthenticationWebView.tsx
> +	const { authType, url, ssoToken } = useRoute<RouteProp<OutsideModalParamList, 'AuthenticationWebView'>>().params;
```suggestion
	const { params: {authType, url, ssoToken} } = useRoute<RouteProp<OutsideModalParamList, 'AuthenticationWebView'>>();
```

2023-05-03 13:27 UTC, GleidsonDaniel commented on app/views/AuthenticationWebView.tsx
> +				onLoadStart={() => {
```suggestion
				onLoadStart={() => setLoading(true)}
```

2023-05-03 13:27 UTC, GleidsonDaniel commented on app/views/AuthenticationWebView.tsx
> +				onLoadEnd={() => {
```suggestion
				onLoadEnd={() => setLoading(false)}
```

2023-05-03 13:27 UTC, GleidsonDaniel commented on app/views/AuthenticationWebView.tsx
> +			headerLeft: () => <HeaderButton.CloseModal navigation={navigation} />,
```suggestion
			headerLeft: () => <HeaderButton.CloseModal />,
```
This component does not need to pass navigation

2023-05-04 17:46 UTC, GleidsonDaniel approved these changes

2023-10-18 17:13 UTC, merged