Add support for tasks and unordered list markdown
RocketChat/Rocket.Chat.ReactNative pull request #5057
Opened 2023-05-05 10:11 UTC by imf-ali

## Issue(s)	
Tasks and unordered list does not appear in correct format as that in RC web app.

## How to test or reproduce
- [x] Tasks should display in expected form
- [x] Unordered list should display in expected form

## Screenshots
Previous behaviour
<img width="267" alt="image" src="https://user-images.githubusercontent.com/42451210/228930970-80c2f57d-a014-49a3-833c-49e4f9b2a790.png">

Improvement
<img width="294" alt="image" src="https://user-images.githubusercontent.com/42451210/228929777-7eac48ac-189a-4c68-afc8-b9ff7f6a778f.png">

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

Fix #4927

2023-05-05 10:15 UTC, imf-ali commented
Hey @diegolmello and @GleidsonDaniel , please have a look at the PR.

2023-05-16 17:21 UTC, imf-ali commented on app/containers/markdown/new/TaskList.tsx
> +						<CheckBox disabled={true} style={{ height: 20, width: 20, margin: 5 }} boxType='square' value={item.status} />
Done.

2023-05-26 07:26 UTC, imf-ali commented
@GleidsonDaniel please have a look at it.

2023-05-26 17:23 UTC, GleidsonDaniel commented
> A quick comment, instead add a new library to the repo, can you use it the same way as other places?
> 
> As you can see here:
> 
> https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/2d07b1682ca8ca06eb1addfc8b6bbd3287f220ae/app/containers/MessageBox/index.tsx#L1119-L1124
> 
> we are using the custom icon for the checkbox

@imf-ali i think this is the best approach.
Change your PR following this pattern commented by @reinaldonetof

2023-05-26 17:24 UTC, GleidsonDaniel requested changes
Change your PR following the pattern commented by @reinaldonetof

2023-05-27 07:01 UTC, imf-ali commented
Changes done. Please have a look @GleidsonDaniel @reinaldonetof .
Preview of the change
<img width="310" alt="image" src="https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/42451210/6a9cc510-0364-4549-accc-78cab7515133">

2023-05-27 10:32 UTC, GleidsonDaniel requested changes

2023-05-27 10:32 UTC, GleidsonDaniel commented on ios/Podfile.lock
> +  - RNCCheckbox (0.5.15):
update your podfile

2023-05-27 13:38 UTC, imf-ali commented on ios/Podfile.lock
> +  - RNCCheckbox (0.5.15):
Done

2023-05-27 13:39 UTC, imf-ali commented
@GleidsonDaniel comment addressed. Please have a look.

2023-05-27 14:19 UTC, GleidsonDaniel requested changes

2023-05-27 14:19 UTC, GleidsonDaniel commented on ios/Podfile.lock
> +COCOAPODS: 1.11.3
```suggestion
COCOAPODS: 1.12.1
```

2023-05-27 16:14 UTC, imf-ali commented on ios/Podfile.lock
> +COCOAPODS: 1.11.3
Done.

2024-02-05 10:54 UTC, GleidsonDaniel requested changes

2024-02-05 10:54 UTC, GleidsonDaniel commented on app/containers/markdown/new/TaskList.tsx
> +							color='#9297a2'
Don't put the color directly in the code, use a constant, preferably one that is in the app's const colors, as it doesn't change color, add it as a fixed color.

2024-02-05 10:54 UTC, GleidsonDaniel commented on app/containers/markdown/new/TaskList.tsx
> +							testID={item.status ? 'send-to-channel-checked' : 'send-to-channel-unchecked'}
```suggestion
							testID={item.status ? 'task-list-checked' : 'task-list-unchecked'}
```

2024-02-07 15:31 UTC, imf-ali commented
> I saw that you sent me a private message asking for the review. Just pay attention to one issue: Previously your PR was not reviewed because it didn't even pass the lint, so before requesting the PR check that all the steps in the checklist are correct.

Oh, sorry for the inconvenience. Will make sure next time, all the checks are successful. I have addressed the remaining comments. Kindly take a look once.

2024-02-07 21:02 UTC, GleidsonDaniel approved these changes

2024-02-07 21:03 UTC, merged