regression: Revert upgrade to React Native 0.71.7
RocketChat/Rocket.Chat.ReactNative pull request #5162
Opened 2023-08-08 18:14 UTC by diegolmello

## Proposed changes

## Issue(s)	

## How to test or reproduce

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2023-08-09 14:35 UTC, GleidsonDaniel requested changes

2023-08-09 14:35 UTC, GleidsonDaniel commented on push.apns
This here can keep

2023-08-09 16:46 UTC, GleidsonDaniel approved these changes

2023-08-18 17:48 UTC, merged

2023-09-01 07:43 UTC, bhupendra1011 commented
Hi @diegolmello, are you able to push Android app updates to the Play Store after rollback to RN .68? I am also facing performance issues after updating to RN 0.72.4. Also [this](https://www.callstack.com/campaigns/upgrade-your-react-native-version) mentions to have latest react-native for future updates to play store

2023-09-01 11:38 UTC, diegolmello commented
@bhupendra1011 Yes, we're able to update to Play Store even though we're RN 0.68.6.
You just need to target Android SDK 33 to do it.
Officially, React Native started supporting it on 0.70 iirc, but it doesn't stop you from doing it yourself.