fix: check the permissions properly to create a discussion
RocketChat/Rocket.Chat.ReactNative pull request #5217
Opened 2023-09-20 19:14 UTC by reinaldonetof

## Proposed changes

## Issue(s)	

## How to test or reproduce

To do a quick test
- create a user, add him to a channel and give only the channel's moderator role
- also, go to the workspace admin and remove his `user` role

## Screenshots

#### Before
- Rooms List View
<img width="309" alt="Screen Shot 2023-09-20 at 15 27 57" src="https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/998630bf-2c6d-448d-a838-ab9880ac6e9b">

- Message Long Press
<img width="309" alt="Screen Shot 2023-09-20 at 15 35 01" src="https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/eb12b4cd-1dad-4248-9542-aea1300471d4">

- Message Action
<img width="309" alt="Screen Shot 2023-09-20 at 16 13 24" src="https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/0f808f44-4332-4e01-9c03-d1cfede07363">

#### After
- Rooms List View
<img width="309" alt="Screen Shot 2023-09-20 at 15 31 35" src="https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/34d8d6ab-2013-43c0-9c2c-8d9600f0ec57">

- Message Long Press
<img width="309" alt="Screen Shot 2023-09-20 at 15 27 04" src="https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/1c7f1681-9a07-4ad6-b458-857fd7cd77b2">

- Message Action
<img width="309" alt="Screen Shot 2023-09-20 at 15 27 14" src="https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/4423f143-8f0e-41a7-bac8-4f620dead950">

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

[SUP-290]

2023-09-26 11:37 UTC, GleidsonDaniel requested changes
There is nothing wrong with the PR, but the CI is not passing, remember this message: https://open.rocket.chat/group/native-clients-internal?msg=wqMoiAhn7SaPAaYmM
`it's required from the PR's author to have E2E tests passing on CI before asking for review.`

2023-09-26 12:52 UTC, diegolmello submitted a review, later dismissed
If there aren't actions available, we shouldn't show the action sheet at all.
Showing it empty looks like a bug.

Some could argue that long pressing and not displaying the action sheet could still look like a bug, but it's perhaps less buggy? Kind of subjective.
In the future, we should improve this to make it more clear. Not allowing the user to long press or showing a toast with no actions available could do it.

2023-09-28 14:39 UTC, reinaldonetof commented
> If there aren't actions available, we shouldn't show the action sheet at all. Showing it empty looks like a bug.
> 
> Some could argue that long pressing and not displaying the action sheet could still look like a bug, but it's perhaps less buggy? Kind of subjective. In the future, we should improve this to make it more clear. Not allowing the user to long press or showing a toast with no actions available could do it.

https://rocketchat.atlassian.net/browse/TC-974

2023-10-13 16:34 UTC, GleidsonDaniel approved these changes

2023-10-16 20:55 UTC, merged