fix: remove the blur view
RocketChat/Rocket.Chat.ReactNative pull request #5475
Opened 2024-01-11 15:31 UTC by reinaldonetof

## Proposed changes

As mentioned here: https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/5420#issuecomment-1864869943
The react-native-blur component has a performance impact on Android devices. Therefore, to improve performance, we opted to replace the blur view with a simple view set to 80% opacity for the background, as per the design team's recommendation.

## Issue(s)	

Closes https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/5420

## How to test or reproduce

- Go to a direct chat with somebody where a lot of images were shared.
- Just use the app a bit: go back; observe your chats

## Screenshots

#### Before
![image](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/bbf8f38e-f33e-4af0-bfae-63f4cc793316)

#### After
![image](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/221d11e2-bcec-4410-a38d-337ce0ce8012)

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

[TC-1066]

2024-01-15 16:35 UTC, GleidsonDaniel requested changes
It is necessary to remove the blur library as it is no longer in use.

2024-01-16 16:17 UTC, diegolmello requested changes
I'm sorry if you did already and I couldn't find, but without an actual benchmark confirming this change has a performance impact, this fix looks like guessing.
You could do:
- record before/after and place videos side by side
- do flashlight.dev

2024-01-17 13:21 UTC, reinaldonetof commented
> I'm sorry if you did already and I couldn't find, but without an actual benchmark confirming this change has a performance impact, this fix looks like guessing. You could do:
> 
> * record before/after and place videos side by side
> * do flashlight.dev

I recorded a video

Before

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/a14c7971-23d9-4090-b4a8-ee4e809fb9d6


After 

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/04a1e594-92ea-4980-9fcc-e8280b84637c

2024-01-17 16:08 UTC, diegolmello requested changes

2024-01-17 22:51 UTC, reinaldonetof commented on app/lib/constants/colors.ts
> +		overlayColor: '#1F2329CC',
I talked directly with Jose about this overlayColor, then he told me to change the opacity  and we agreed this opacity hides a bit the image, isn't a blur, but it's far enough for now.

2024-01-18 13:06 UTC, diegolmello commented on app/lib/constants/colors.ts
> +		overlayColor: '#1F2329CC',
You didn't answer the themes part of my question.
I know we don't have Dark theme on Figma, so have you guys tried it there?

2024-01-19 16:19 UTC, GleidsonDaniel commented on app/lib/constants/colors.ts
> +		overlayColor: '#1F2329CC',
I think he wrote it wrong.
It's not a blur, but it's enough for the current situation.

2024-01-19 16:21 UTC, GleidsonDaniel commented on app/lib/constants/colors.ts
> +		overlayColor: '#1F2329CC',
Regarding the color, I don't think it needs a theme, a gray mask is gray regardless of the theme.
Since it is a simulation of a bur.

2024-01-22 13:48 UTC, diegolmello approved these changes

2024-01-22 21:53 UTC, merged