Fix - Prevent Updating Name, Username, Email, and New Password with Empty/Whitespace Values
RocketChat/Rocket.Chat.ReactNative pull request #5544
Opened 2024-02-06 15:54 UTC by anirbanpaulcom

## Proposed changes

## Issue(s)	

## How to test or reproduce

## Screenshots

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2024-02-06 16:27 UTC, diegolmello requested changes
Your PR fixes an issue, but it should be using `react-hook-form` https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/aa3938a2a46a3694f874350c6aaf73062a114e3c/app/views/CreateChannelView/index.tsx#L86

Can you migrate this component?

2024-02-13 09:21 UTC, anirbanpaulcom commented
> Your PR fixes an issue, but it should be using `react-hook-form`
> 
> https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/aa3938a2a46a3694f874350c6aaf73062a114e3c/app/views/CreateChannelView/index.tsx#L86
> 
> Can you migrate this component?

 @diegolmello Can you please tell me how to migrate it because the React Hook 'useForm' cannot be called in a class component, or should I wrap it?

2024-02-16 14:44 UTC, anirbanpaulcom commented
> Your PR fixes an issue, but it should be using `react-hook-form`
> 
> https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/aa3938a2a46a3694f874350c6aaf73062a114e3c/app/views/CreateChannelView/index.tsx#L86
> 
> Can you migrate this component?

@diegolmello  Can you please tell me how to migrate it because the React Hook 'useForm' cannot be called in a class component, or should I wrap it?

2024-02-16 15:59 UTC, diegolmello commented
Hey @anirbanpaulcom.
Can you migrate the component to hooks on another PR and then use react-hook-form?
Thanks!

2024-04-08 17:25 UTC, anirbanpaulcom commented
> Hey @anirbanpaulcom.
> Can you migrate the component to hooks on another PR and then use react-hook-form?
> Thanks!

@diegolmello , Please take a look, PR : #5646

2025-02-25 12:47 UTC, diegolmello commented on app/views/ProfileView/index.tsx
> +
```suggestion
```

2025-02-25 12:47 UTC, diegolmello approved these changes

2025-02-25 12:49 UTC, merged