fix: corrects hanging on white screen at startup #5786
RocketChat/Rocket.Chat.ReactNative pull request #5788
Opened 2024-07-12 21:41 UTC by sanyappc

* fix: corrects hanging on white screen at startup

2024-07-12 21:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative?pullRequest=5788) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative?pullRequest=5788) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.ReactNative?pullRequest=5788) it.</sub>

2024-07-12 21:47 UTC, sanyappc commented
#5786

2024-07-13 00:37 UTC, GleidsonDaniel requested changes

2024-07-13 00:37 UTC, GleidsonDaniel commented on app/stacks/OutsideStack.tsx
> +			{/* <Outside.Screen name='NewServerView' component={NewServerView} options={NewServerView.navigationOptions} /> */}
```suggestion

```

2024-07-15 13:19 UTC, diegolmello commented on app/stacks/OutsideStack.tsx
> +			{/* <Outside.Screen name='NewServerView' component={NewServerView} options={NewServerView.navigationOptions} /> */}
Commenting is ok

2024-07-15 13:19 UTC, diegolmello approved these changes

2024-07-15 13:19 UTC, merged

2024-07-15 13:20 UTC, diegolmello commented
Merged. Thanks for your contribution, @sanyappc!