feat: Help page
RocketChat/Rocket.Chat.ReactNative pull request #5855
Opened 2024-09-04 09:43 UTC by yash-rajpal

## Proposed changes

## Issue(s)	

## How to test or reproduce

## Screenshots
![image](https://github.com/user-attachments/assets/c3312674-6fd4-4d34-a826-2243eba7bb08)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] I have added necessary documentation (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

[MA-71](https://rocketchat.atlassian.net/browse/MA-71)

2024-09-05 16:32 UTC, diegolmello requested changes
Missing E2E tests

2024-09-05 16:32 UTC, diegolmello commented on app/views/SettingsView/index.tsx
> +					title='Media_auto_download'
Unwanted indentation

2024-09-05 16:32 UTC, diegolmello commented on app/views/GetHelpView.tsx
> +						right={() => <List.Icon name='new-window' style={I18nManager.isRTL ? { transform: [{ rotate: '180deg' }] } : null}/>}
Do we need to rotate the icon on RTL?

2024-09-05 16:32 UTC, diegolmello commented on app/i18n/locales/en.json
> +  "Accessibility_statement": "Accessibility statement",
Can you add i18n for other languages using AI?
It's not perfect, but it's better than not having it translated.

2024-09-16 19:27 UTC, yash-rajpal commented on e2e/tests/assorted/04-setting.spec.ts
> +		it('should have get help', async () => {
kkkk

2024-09-16 19:28 UTC, yash-rajpal commented on app/views/SettingsView/index.tsx
> +						right={() => <List.Icon name='new-window' />}
I'm not sure, maybe we should as the icon is pointing outwards.

I'll confirm with the design team.

2024-09-18 14:38 UTC, yash-rajpal commented on app/views/SettingsView/index.tsx
> +						right={() => <List.Icon name='new-window' />}
Confirmed with design team, it should always point outwards, should point left when UI is RTL.

Created a new component and using it everywhere

2024-09-24 17:23 UTC, diegolmello approved these changes

2024-09-24 17:23 UTC, merged