feat: crated thumbnail using expo-video-thumbnail
RocketChat/Rocket.Chat.ReactNative pull request #5893
Opened 2024-10-02 21:15 UTC by OtavioStasiak

## Proposed changes

Create a thumbnail to improve the video component UX.

## Issue(s)	

https://rocketchat.atlassian.net/browse/NATIVE-226

## How to test or reproduce

- Open the app;
- Open a room that has a video;

## Screenshots

### IOS:

#### Before:

https://github.com/user-attachments/assets/bac0bbbe-814b-4873-8151-f85643ae94a7

#### After:

https://github.com/user-attachments/assets/1be27373-a70d-464f-a2a5-2e4cb48b86b3

### Android:

#### Before:
[android_before.webm](https://github.com/user-attachments/assets/c3144e25-2103-48e6-8ba3-ca5f60e591ec)

#### After:
[videoPrAndroid.webm](https://github.com/user-attachments/assets/55a70e63-db20-4003-86e1-b84573e10c09)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] Improvement (non-breaking change which improves a current function)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [X] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [X] Lint and unit tests pass locally with my changes
- [X] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [X] I have added necessary documentation (if applicable)
- [X] Any dependent changes have been merged and published in downstream modules

## Further comments

2024-10-02 21:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative?pullRequest=5893) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative?pullRequest=5893) before we can accept your contribution.<br/><hr/>**Otavio Stasiak** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.ReactNative?pullRequest=5893) it.</sub>

2024-10-03 13:17 UTC, diegolmello requested changes
Almost there.
Lint is failing.

2024-10-03 13:17 UTC, diegolmello commented on app/containers/message/Components/Attachments/Thumbnail.tsx
> +		shadowColor: '#000',
Don't use fixed colors. Everything should come from themes.

2024-10-03 13:17 UTC, diegolmello commented on app/containers/message/Components/Attachments/Thumbnail.tsx
> +		width: '100%',
Can you use flex?

2024-10-03 13:17 UTC, diegolmello commented on app/containers/message/Components/Attachments/Thumbnail.tsx
> +const Thumbnail = ({ url, encrypted = false }: ThumbnailProps) => {
You asked my opinion about splitting Thumbnail in a separate file.
I said we should either keep on Video file (it's a small file, so it's ok) or we create a Video folder so `message/Components/Attachments` is organized with one file per feature.

You create `Thumbnail` file without a Video folder, so Attachments now have 
```
- CollapsibleQuote (folder)
- Image (folder) 
- AttachedActions.tsx
- Attachments.tsx
- Audio.tsx
- Reply.tsx
- Video.tsx
- Thumbnail.tsx (this one is only related to Video)
```

2024-10-16 13:38 UTC, diegolmello requested changes

2024-10-16 13:38 UTC, diegolmello commented on app/containers/message/Components/Attachments/Video.tsx
> +type Image = string | null;
```suggestion
type TThumbnailImage = string | null;
```

2024-10-16 13:38 UTC, diegolmello commented on app/containers/message/Components/Attachments/Video.tsx
> +		shadowColor: themes.light.backdropColor,
light?

2024-10-16 13:38 UTC, diegolmello commented on app/containers/message/Components/Attachments/Video.tsx
> +		shadowOpacity: 0.3,
use theme

2024-10-22 21:06 UTC, diegolmello commented on app/containers/message/Components/Attachments/Video.tsx
> +							{ shadowColor: themes[theme].backdropColor, shadowOpacity: themes[theme].backdropOpacity }
Missing shadow or elevation on Android.

2024-10-22 21:06 UTC, diegolmello approved these changes
One last missing change requested and you can merge it.

2024-10-25 17:41 UTC, OtavioStasiak commented on app/containers/message/Components/Attachments/Video.tsx
> +							{ shadowColor: themes[theme].backdropColor, shadowOpacity: themes[theme].backdropOpacity }
fixed.

2024-10-25 17:45 UTC, merged